---
title: "BC Cleaning"
author: "Ethan Walker"
date: "November 8, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(caTools)
```

#Read in BC files
```{r, message=FALSE}
r00_phase1_bc_post <- read_csv("input/r00_phase1_bc_post.csv")
r00_phase2_bc_post <- read_csv("input/r00_phase2_bc_post.csv")
r00_phase2_bc_pre <- read_csv("input/r00_phase2_bc_pre.csv")
r00_phase3_bc_post <- read_csv("input/r00_phase3_bc_post.csv")
r00_phase3_bc_pre <- read_csv("input/r00_phase3_bc_pre.csv")
r00_phase4_bc_post <- read_csv("input/r00_phase4_bc_post.csv")
r00_phase4_bc_pre <- read_csv("input/r00_phase4_bc_pre.csv")
r00_phase5_bc_post <- read_csv("input/r00_phase5_bc_post.csv")
r00_phase5_bc_pre <- read_csv("input/r00_phase5_bc_pre.csv")
r00_phase6_bc_post <- read_csv("input/r00_phase6_bc_post.csv")
#r00_phase6_bc_pre <- read_csv("input/r00_phase6_bc_pre.csv") #pre-scans for phase 6 currently missing
```

#Read in BC files
```{r}
r00_phase2_bc <- full_join(r00_phase2_bc_pre, r00_phase2_bc_post, by = "filter_id")
# should the blank filters with ID beginning "L" actually begin "BL"?

r00_phase3_bc <- full_join(r00_phase3_bc_pre, r00_phase3_bc_post, by = "filter_id")

r00_phase4_bc <- full_join(r00_phase4_bc_pre, r00_phase4_bc_post, by = "filter_id")

r00_phase5_bc <- full_join(r00_phase5_bc_pre, r00_phase5_bc_post, by = "filter_id")

#r00_phase6_bc <- full_join(r00_phase6_bc_pre, r00_phase6_bc_post, by = "filter_id")
#pre-scans for phase 6 currently missing
```

#save data
```{r}
#write_csv(r00_phase1_bc, "output/r00_phase1_bc.csv") #we didn't pre-scan for phase 1
write_csv(r00_phase2_bc, "output/r00_phase2_bc.csv", na = " ")
write_csv(r00_phase3_bc, "output/r00_phase3_bc.csv", na = " ")
write_csv(r00_phase4_bc, "output/r00_phase4_bc.csv", na = " ")
write_csv(r00_phase5_bc, "output/r00_phase5_bc.csv", na = " ")
#write_csv(r00_phase6_bc, "output/r00_phase6_bc.csv") #pre-scans for phase 6 currently missing
```

