---
title: "R00 Sphygmocor Initial Cleaning"
author: "Ethan Walker"
date: "December 20, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

# Libraries

```{r}
  library(tidyverse)
  library(magrittr)
  library(gridExtra)
  library(lubridate)
  library(haven)
  library(knitr)
```

---

# Load Sphygmocor Files

```{r}
#p6_patient <- read_csv("input/sphygmocor/r00_p6_sphygmo_patient.csv") 

#p6_pwa <- read_csv("input/sphygmocor/r00_p6_sphygmo_pwa.csv") 

#r00_full_long <- read_rds("output/r00_full_repeated_by_phase.rds")

#Not using for now
#p6_cpwa <- read_csv("input/sphygmocor/r00_p6_sphygmo_cpwa.csv")

#load full, joined dataset
r00_full_joined_sphygmocor <- read_rds("output/r00_full_joined_sphygmocor.RDS")
```


## Participants - extract study id, sphygmocor id, date of birth
```{r}
r00_participant_info <- p6_patient %>% 
  select(PatientNumberInternal, PatientIDExternalReference) %>% 
  rename(id_sphygmo = PatientNumberInternal,
         house_id = PatientIDExternalReference) %>% 
  mutate(id_sphygmo = as.numeric(id_sphygmo)) %>% 
  #remove test id's
  mutate(id_sphygmo = if_else(id_sphygmo == 246, 999999, id_sphygmo)) %>% 
  mutate(id_sphygmo = if_else(id_sphygmo == 247, 999999, id_sphygmo)) %>% 
  mutate(id_sphygmo = if_else(id_sphygmo == 248, 999999, id_sphygmo)) %>% 
  mutate(id_sphygmo = if_else(id_sphygmo == 249, 999999, id_sphygmo)) %>% 
  filter(id_sphygmo < 1000)
```

## PWA - join with participant info and clean up
```{r}
r00_pwa <- p6_pwa %>%
  rename_all(tolower) %>% 
  rename(id_sphygmo = patientnumberinternal,
         datetime_sphygmo = studydatetime) %>%
  #join with participant info
  left_join(r00_participant_info, by = "id_sphygmo") %>%
  mutate(date = as.Date(datetime_sphygmo), week_of_year = lubridate::isoweek(date)) %>%
  mutate(date_sphygmo = ymd(date), datetime_sphygmo = ymd_hms(datetime_sphygmo)) %>% 
  select(house_id, date_sphygmo, date, datetime_sphygmo, week_of_year, id_sphygmo, hr, sp, dp, mp, 
         c_sp, c_dp, c_meanp,c_ai, c_ap, c_mps, c_mpd, c_esp, c_agph) %>%
  rename(sys_bp_periph = sp, dia_bp_periph = dp, sys_bp_central = c_sp, 
         dia_bp_central = c_dp, map_central = c_meanp, aug_index = c_agph,
         aug_pressure = c_ap, map_periph = mp) %>% 
  select(-c_ai, -c_mpd, -c_mps, -c_esp, - date) %>% 
  #create new variables
  mutate(pulse_pressure_periph = (sys_bp_periph - dia_bp_periph),
         pulse_pressure_central = (sys_bp_central - dia_bp_central),
         aug_index_75 = if_else(hr < 75, aug_index - (((75 - hr)/10)*4.8), 
                         aug_index - (((75 - hr)/10)*4.8))) %>% 
  na.exclude(house_id) %>% 
  #removing session with duplicate aug_index measurement
  mutate(aug_index = if_else(house_id == "QDL008" & date_sphygmo == "2018-04-26", 99999, aug_index)) %>% 
  filter(aug_index < 9999) %>% 
  #round variables to 2 digits
  mutate(hr = round(hr, digits = 2), 
         sys_bp_central = round(sys_bp_central, digits = 2), 
         dia_bp_central = round(dia_bp_central, digits = 2),
         map_central = round(map_central, digits = 2), 
         aug_pressure = round(aug_pressure, digits = 2), 
         aug_index = round(aug_index, digits = 2),
         pulse_pressure_central = round(pulse_pressure_central, digits = 2), 
         aug_index_75 = round(aug_index_75, digits = 2)) %>% 
  arrange(house_id, datetime_sphygmo)
```

## Sphygmocor Summary Stats
```{r}
sphygmo_summary <- r00_pwa %>% 
  na.exclude(aug_index) %>% 
  summarise(mean(hr), median(hr), max(hr), min(hr),
            mean(sys_bp_periph), median(sys_bp_periph), max(sys_bp_periph), min(sys_bp_periph),
            mean(dia_bp_periph), median(dia_bp_periph), max(dia_bp_periph), min(dia_bp_periph),
            mean(map_periph), median(map_periph), max(map_periph), min(map_periph),
            mean(sys_bp_central), median(sys_bp_central), max(sys_bp_central), min(sys_bp_central),
            mean(dia_bp_central), median(dia_bp_central), max(dia_bp_central), min(dia_bp_central),
            mean(map_central), median(map_central), max(map_central), min(map_central),
            mean(aug_pressure), median(aug_pressure), max(aug_pressure), min(aug_pressure),
            mean(aug_index), median(aug_index), max(aug_index), min(aug_index),
            mean(aug_index_75), median(aug_index_75), max(aug_index_75), min(aug_index_75),
            mean(pulse_pressure_central), median(pulse_pressure_central), max(pulse_pressure_central),
            min(pulse_pressure_central),
            mean(pulse_pressure_periph), median(pulse_pressure_periph), max(pulse_pressure_periph),
            min(pulse_pressure_periph))
sphygmo_summary
```

## Make sure systolic pressures are > diastolic
```{r}
bp_check <- r00_pwa %>% 
  mutate(periph_bp_check = if_else(dia_bp_central > sys_bp_central, 1, 0)) %>% 
  mutate(central_bp_check = if_else(dia_bp_periph > sys_bp_periph, 1, 0)) %>% 
  summarise(sum(periph_bp_check), sum(central_bp_check))
bp_check
```

## Further cleaning - make sure correct number of observations per house_id
```{r}
r00_check <- r00_full_long %>% 
  separate(date, c("day_week", "month", "day", "time", "utc", "year"), sep = " ") %>% 
  unite(date_new, c("year", "month", "day"), sep = "") %>% 
  #mutate(date = ymd(date_new)) %>% 
  mutate(date_sphygmo = ymd(date_new) + days(1)) %>% 
  select(-"day_week", -"time", -"utc", -"date_new") %>% 
  left_join(r00_pwa, by = c("house_id", "date_sphygmo")) %>% 
  select(house_id, date_sphygmo, phase, augmentation_index, aug_index) %>% 
  mutate(augmentation_index = as.numeric(augmentation_index)) %>% 
  mutate(aug_index = as.numeric(aug_index)) %>% 
  mutate(augmentation_index = if_else(is.na(augmentation_index), 0, augmentation_index)) %>% 
  mutate(aix_check = if_else(aug_index > -100, 1, 0)) %>% 
  #filtering out NAs: left with 1,163 observations with Sphygmocor data
  filter(aug_index < 1000) 

# According to augmentation_index variable there are 12 instances where we
# don't have aug_index data but should, and 2 instances where we do have
# aug_index data but should not

# CAC007 - 2016-09-22 should be 2016-09-23
# CER064 - 2017-04-11 should be 2017-04-12
# CER067 - 2018-04-17 no data 
# HOR041 - 2016-09-08 should be 2016-09-10
# OLO007 - 2016-10-21 should be 2016-10-22
# PER005 - 2018-04-20 no data
# PER052 - 2016-11-18 should be 2016-11-19
# QDL007 - 2018-04-26 no data
# QDL012 - 2017-04-27 should be 2017-04-28
# ZAC014 - 2015-09-05 should be 2015-09-07
# ZAC017 - 2018-03-07 have data for 2018-02-16 - off by too much so won't use
# ZAC027 - 2015-09-10 should be 2015-09-11

r00_check <- r00_full_long %>% 
  separate(date, c("day_week", "month", "day", "time", "utc", "year"), sep = " ") %>% 
  unite(date_new, c("year", "month", "day"), sep = "") %>% 
  #mutate(date = ymd(date_new)) %>% 
  mutate(date_sphygmo = ymd(date_new) + days(1)) %>% 
  #fix incorrect dates described above
  mutate(date_sphygmo = if_else(house_id == "CAC007" & date_sphygmo == "2016-09-22",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "CER064" & date_sphygmo == "2017-04-11",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "HOR041" & date_sphygmo == "2016-09-08",
                               date_sphygmo + days(2), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "OLO007" & date_sphygmo == "2016-10-21",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "PER052" & date_sphygmo == "2016-11-18",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "QDL012" & date_sphygmo == "2017-04-27",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "ZAC014" & date_sphygmo == "2015-09-05",
                               date_sphygmo + days(2), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "ZAC027" & date_sphygmo == "2015-09-10",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  select(-"day_week", -"time", -"utc", -"date_new") %>% 
  left_join(r00_pwa, by = c("house_id", "date_sphygmo")) %>% 
  select(house_id, date_sphygmo, phase, augmentation_index, aug_index) %>% 
  mutate(augmentation_index = as.numeric(augmentation_index)) %>% 
  mutate(aug_index = as.numeric(aug_index)) %>% 
  mutate(augmentation_index = if_else(is.na(augmentation_index), 0, augmentation_index)) %>% 
  mutate(aix_check = if_else(aug_index > -100, 1, 0)) %>% 
  #filtering out NAs: left with 1,171 observations with Sphygmocor data
  filter(aug_index < 1000) 
  
table(r00_check$aix_check)
# Number of house_ids is correct
n_distinct(r00_check$house_id)

# Now performing the above cleaning on full dataset
r00_joined <- r00_full_long %>% 
  mutate(date_new = date) %>% 
  separate(date_new, c("day_week", "month", "day", "time", "utc", "year"), sep = " ") %>% 
  unite(date_new, c("year", "month", "day"), sep = "") %>% 
  mutate(date_setup = ymd(date_new)) %>% 
  mutate(date_sphygmo = ymd(date_new) + days(1)) %>% 
  #fix incorrect dates described above
  mutate(date_sphygmo = if_else(house_id == "CAC007" & date_sphygmo == "2016-09-22",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "CER064" & date_sphygmo == "2017-04-11",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "HOR041" & date_sphygmo == "2016-09-08",
                               date_sphygmo + days(2), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "OLO007" & date_sphygmo == "2016-10-21",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "PER052" & date_sphygmo == "2016-11-18",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "QDL012" & date_sphygmo == "2017-04-27",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "ZAC014" & date_sphygmo == "2015-09-05",
                               date_sphygmo + days(2), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "ZAC027" & date_sphygmo == "2015-09-10",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  select(-"day_week", -"time", -"utc", -"date_new") %>% 
  left_join(r00_pwa, by = c("house_id", "date_sphygmo"))
```

# Fix incorrect height/bmi in database
```{r}
r00_joined <- r00_full_joined_sphygmocor %>% 
  ##### need to fix this in the main database #####
  mutate(height = as.numeric(height)) %>% 
  mutate(weight = as.numeric(weight)) %>% 
  mutate(height = if_else(phase == 6 & house_id == "CER009", 57.0, height)) %>% 
  mutate(bmi = (weight*0.453592)/((height*0.0254)^2)) 
```


# Output
```{r}
# .RDS
write_rds(r00_pwa,
            "output/r00_sphygmocor_pwa.RDS")
write_rds(r00_joined,
            "output/r00_full_joined_sphygmocor.RDS")
# .csv
write_csv(r00_pwa,
            "output/r00_sphygmocor_pwa.csv", na = " ")
write_csv(r00_joined,
            "output/r00_full_joined_sphygmocor.csv", na = " ")
# .sas7bdat
write_sas(r00_pwa,
            "output/r00_sphygmocor_pwa.sas7bdat")
write_sas(r00_joined,
            "output/r00_full_joined_sphygmocor.sas7bdat")
```