---
title: "Initial Data Cleaning"
author: "Ethan Walker"
date: "6 August 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
```

```{r, message=FALSE}
# Load data
#r00_full_wide <- read_xlsx("input/R00_health_wide_15Jan2019_by.xlsx")

r00_full_wide <- readRDS("output/r00_full_wide.rds")
```

##### Convert Dataset from Wide to Long #####
```{r}
r00_full_long <- r00_full_wide %>% 
  #creating new variables for phases 2-6 if it was only collected at phase 1
  mutate(electricity_r00_p2 = electricity_r00_p1, 
         electricity_r00_p3 = electricity_r00_p1, 
         electricity_r00_p4 = electricity_r00_p1, 
         electricity_r00_p5 = electricity_r00_p1, 
         electricity_r00_p6 = electricity_r00_p1) %>%
  mutate(school_bi_r00_p2 = school_bi_r00_p1, 
         school_bi_r00_p3 = school_bi_r00_p1, 
         school_bi_r00_p4 = school_bi_r00_p1, 
         school_bi_r00_p5 = school_bi_r00_p1, 
         school_bi_r00_p6 = school_bi_r00_p1) %>%
  mutate(community_cat_r00_p2 = community_cat_r00_p1, 
         community_cat_r00_p3 = community_cat_r00_p1, 
         community_cat_r00_p4 = community_cat_r00_p1, 
         community_cat_r00_p5 = community_cat_r00_p1, 
         community_cat_r00_p6 = community_cat_r00_p1) %>%
  mutate(birth_year_r00_p2 = birth_year_r00_p1, 
         birth_year_r00_p3 = birth_year_r00_p1, 
         birth_year_r00_p4 = birth_year_r00_p1, 
         birth_year_r00_p5 = birth_year_r00_p1, 
         birth_year_r00_p6 = birth_year_r00_p1) %>%
  rename(beds_new_r00_p1 = beds_new) %>% 
  mutate(beds_new_r00_p2 = beds_new_r00_p1, 
         beds_new_r00_p3 = beds_new_r00_p1, 
         beds_new_r00_p4 = beds_new_r00_p1, 
         beds_new_r00_p5 = beds_new_r00_p1, 
         beds_new_r00_p6 = beds_new_r00_p1) %>%
  mutate(indigenous_r00_p2 = indigenous_r00_p1, 
         indigenous_r00_p3 = indigenous_r00_p1, 
         indigenous_r00_p4 = indigenous_r00_p1, 
         indigenous_r00_p5 = indigenous_r00_p1, 
         indigenous_r00_p6 = indigenous_r00_p1) %>%
  mutate(school_self_r00_p2 = school_self_r00_p1, 
         school_self_r00_p3 = school_self_r00_p1, 
         school_self_r00_p4 = school_self_r00_p1, 
         school_self_r00_p5 = school_self_r00_p1, 
         school_self_r00_p6 = school_self_r00_p1) %>%
  mutate(elevation_r00_p2 = elevation_r00_p1, 
         elevation_r00_p3 = elevation_r00_p1, 
         elevation_r00_p4 = elevation_r00_p1, 
         elevation_r00_p5 = elevation_r00_p1, 
         elevation_r00_p6 = elevation_r00_p1) %>% 
  mutate(sex_r00_p2 = sex_r00_p1, 
         sex_r00_p3 = sex_r00_p1, 
         sex_r00_p4 = sex_r00_p1, 
         sex_r00_p5 = sex_r00_p1, 
         sex_r00_p6 = sex_r00_p1) %>% 
  mutate(pers_info_r00_p2 = pers_info_r00_p1, 
         pers_info_r00_p3 = pers_info_r00_p1, 
         pers_info_r00_p4 = pers_info_r00_p1, 
         pers_info_r00_p5 = pers_info_r00_p1, 
         pers_info_r00_p6 = pers_info_r00_p1) %>% 
  rename(ses_materials_r00_p1 = ses_materials) %>% 
  mutate(ses_materials_r00_p2 = ses_materials_r00_p1, 
         ses_materials_r00_p3 = ses_materials_r00_p1, 
         ses_materials_r00_p4 = ses_materials_r00_p1, 
         ses_materials_r00_p5 = ses_materials_r00_p1, 
         ses_materials_r00_p6 = ses_materials_r00_p1) %>%
  mutate(study_arm_r00_p1 = Study_Arm_r00_p2, 
         study_arm_r00_p2 = Study_Arm_r00_p2,
         study_arm_r00_p3 = Study_Arm_r00_p2, 
         study_arm_r00_p4 = Study_Arm_r00_p2, 
         study_arm_r00_p5 = Study_Arm_r00_p2, 
         study_arm_r00_p6 = Study_Arm_r00_p2) %>% 
  mutate(age_baseline_r00_p2 = age_baseline_r00_p1, 
         age_baseline_r00_p3 = age_baseline_r00_p1,
         age_baseline_r00_p4 = age_baseline_r00_p1, 
         age_baseline_r00_p5 = age_baseline_r00_p1, 
         age_baseline_r00_p6 = age_baseline_r00_p1) %>% 
  select(-Study_Arm_r00_p2) %>% 
  #transform data to long format with only 3 columns
  gather(key = "variable", value = "value", -house_id) %>% 
  #arrange data by house_id, descending
  arrange(house_id)

r00_full_repeated_by_phase <- r00_full_long %>%
  #this variable has no corresponding phase
  #renaming to phase 1 so it spreads below
  mutate(variable = if_else(variable == "group", 
                            "group_r00_p1", variable)) %>%
  #separate variable to create new phase column
  separate(variable, c("variable", "phase"), sep = "_r00_p") %>%
  mutate(value = if_else(value == ".", "99999", value)) %>% 
  replace_with_na(replace = list(value = 99999)) %>% 
  #separate phase and "new", then attach "new" to variable
  separate(phase, c("phase", "new"), sep = "_") %>% 
  unite("variable", c("variable", "new")) %>% 
  #remove NA from end of variables that was added above
  separate(variable, c("variable", "trash"), sep = "_NA") %>% 
  select(-"trash") %>% 
  #spread out into columns, grouped by house_id and phase
  spread(key = "variable", value = "value") %>% 
  arrange(house_id) 

# Check number of house_id
n_distinct(r00_full_repeated_by_phase$house_id)
```

# Combine with cleaned Sphygmocor and SUMs datasets
```{r}
r00_sums_full_dataset <- readRDS("output/r00_sums_full_dataset.rds")
r00_pwa <- readRDS("output/r00_sphygmocor_pwa.rds")

  
r00_joined <- r00_full_repeated_by_phase %>% 
  #create new date var (tidy format) to merge with sphygmocor dataset
  mutate(date_new = date) %>% 
  separate(date_new, c("day_week", "month", "day", "time", "utc", "year"), sep = " ") %>% 
  unite(date_new, c("year", "month", "day"), sep = "") %>% 
  mutate(date_setup = ymd(date_new)) %>% 
  mutate(date_sphygmo = ymd(date_new) + days(1)) %>% 
  #fix incorrect dates described in "r00_initial_sphygmocor_cleaning" so merge will line up 
  mutate(date_sphygmo = if_else(house_id == "CAC007" & date_sphygmo == "2016-09-22",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "CER064" & date_sphygmo == "2017-04-11",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "HOR041" & date_sphygmo == "2016-09-08",
                               date_sphygmo + days(2), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "OLO007" & date_sphygmo == "2016-10-21",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "PER052" & date_sphygmo == "2016-11-18",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "QDL012" & date_sphygmo == "2017-04-27",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "ZAC014" & date_sphygmo == "2015-09-05",
                               date_sphygmo + days(2), date_sphygmo)) %>% 
  mutate(date_sphygmo = if_else(house_id == "ZAC027" & date_sphygmo == "2015-09-10",
                               date_sphygmo + days(1), date_sphygmo)) %>% 
  select(-"day_week", -"time", -"utc", -"date_new") %>% 
  #join with cleaned pwa dataset
  left_join(r00_pwa, by = c("house_id", "date_sphygmo")) %>% 
  ##### Fix incorrect height/bmi in database #####
  ##### need to fix this in the main database #####
  mutate(height = as.numeric(height)) %>% 
  mutate(weight = as.numeric(weight)) %>% 
  mutate(height = if_else(phase == 6 & house_id == "CER009", 57.0, height)) %>% 
  mutate(bmi = (weight*0.453592)/((height*0.0254)^2)) %>% 
  #join with cleaned sums dataset
  left_join(r00_sums_full_dataset, by = c("house_id", "phase"))
```


# Save datasets
```{r}
write_rds(r00_full_wide, "output/r00_full_wide.rds")
write_rds(r00_full_long, "output/r00_full_long.rds")
write_rds(r00_joined, "output/r00_full_repeated_by_phase.rds")
write_csv(r00_full_wide, "output/r00_full_wide.csv")
write_csv(r00_full_long, "output/r00_full_long.csv")
write_csv(r00_joined, "output/r00_full_repeated_by_phase.csv", na = " ")
```