---
title: "Honduras R00 Intent-to-treat Models and Plots"
author: "Ethan Walker"
date: "Updated 5 November 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      fig.width = 8, fig.height = 5)
```


```{r, include=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(purrr)
library(car)
library(forcats)
library(readxl)
library(naniar)
library(splines)
library(lubridate)
library(knitr)
library(influence.ME)
library(boxcoxmix)
library(sjstats)
library(rptR)
jvPalette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

# Intent-to-treat models

```{r}
#load full dataset
 #r00_full_repeated_by_phase <- read_rds("output/r00_full_repeated_by_phase.rds")

# USE THIS DATASET FOR ANALYSES!!!
## Removes values >75 for AIx and CPP, and <-25 for AIx
r00_model_data_outliers_removed <- read_rds("output/r00_model_data_outliers_removed.RDS")
```


```{r}
# Creating datasets for various analyses

r00_model_data <- r00_model_data_outliers_removed %>% 
  # removes 6 observations for participant who wasn't assigned to a study arm
  filter(!is.na(study_arm))  
  # Creating variable for time of Sphygmocor assessment to include in the models
  # separate(datetime_sphygmo, c("date_test", "time_test"), sep = " ") %>% 
  # mutate(time_test = hms(time_test))
  # further removes 196 observations (n=1162)
  # filter(!is.na(aug_index)) 


# Dataset for participants who have AIx data for all 6 Phases (107 participants)
r00_data_6phases <- r00_model_data %>%
  filter(complete_case_aix == 1)
  

# Dataset for participants who have AIx data for all <6 Phases
r00_data_5phases <- r00_model_data %>%
  filter(complete_case_aix == 0) 


# Dataset removing 46 participants who missed AIx in phase 2 from sphygmo malfunction
r00_data_sphygmo_p2 <- r00_model_data_outliers_removed %>%
  # removes 6 observations for participant who wasn't assigned to a study arm
  filter(!is.na(study_arm)) %>% 
  mutate(sphygmo_missing_phase2 = as.numeric(sys_bp_final_nurse),
         sphygmo_missing_phase2 = if_else(sphygmo_missing_phase2 > 1, 1, 0),
         sphygmo_missing_phase2 = if_else(is.na(sphygmo_missing_phase2),
                                          0, sphygmo_missing_phase2)) %>%
  group_by(house_id) %>%
  filter(sum(sphygmo_missing_phase2) == 0) %>% 
  ungroup() %>% 
  filter(!is.na(aug_index))  # 949 obs from 184 participants  


# Filtering out medication users (n=34 obs)
r00_model_data_meds <- r00_model_data %>% 
  #filtering out bp med users
  filter(is.na(med_bp)) 


# Dataset where Phase 1 AIx observations are added as a new variable/column
r00_model_data_aix_baseline <- r00_model_data %>% 
  filter(!is.na(aug_index)) %>% 
  group_by(house_id) %>% 
  mutate(baseline_aix = if_else(phase == 1, aug_index, 9999)) %>% 
  mutate(baseline_aix_2 = lag(baseline_aix)) %>% 
  mutate(baseline_aix_3 = lag(baseline_aix_2)) %>% 
  mutate(baseline_aix_2 = if_else(baseline_aix_3 < 9999 & !is.na(baseline_aix_3), 
                                  baseline_aix_3, baseline_aix_2)) %>% 
  mutate(baseline_aix_3 = lag(baseline_aix_2)) %>% 
  mutate(baseline_aix_2 = if_else(baseline_aix_3 < 9999 & !is.na(baseline_aix_3), 
                                  baseline_aix_3, baseline_aix_2)) %>% 
  mutate(baseline_aix_3 = lag(baseline_aix_2)) %>% 
  mutate(baseline_aix_2 = if_else(baseline_aix_3 < 9999 & !is.na(baseline_aix_3), 
                                  baseline_aix_3, baseline_aix_2)) %>% 
  mutate(baseline_aix_3 = lag(baseline_aix_2)) %>% 
  mutate(baseline_aix_2 = if_else(baseline_aix_3 < 9999 & !is.na(baseline_aix_3), 
                                  baseline_aix_3, baseline_aix_2)) %>% 
  filter(phase != 1) %>% 
  mutate(baseline_aix = baseline_aix_2) %>% 
  select(-baseline_aix_2, -baseline_aix_3) 


# Filtering data for each specific phase
r00_model_data_baseline <- r00_model_data %>% 
  filter(phase == 1)
r00_model_data_p2 <- r00_model_data %>% 
  filter(phase == 2)
r00_model_data_p3 <- r00_model_data %>% 
  filter(phase == 3)
r00_model_data_p4 <- r00_model_data %>% 
  filter(phase == 4)
r00_model_data_p5 <- r00_model_data %>% 
  filter(phase == 5)
r00_model_data_p6 <- r00_model_data %>% 
  filter(phase == 6)
```


```{r, eval=FALSE}
# Simple linear models between AIx and age/bmi
aix_age <- lm(aug_index ~ age_baseline, data = r00_model_data_baseline)
tidy(aix_age)
aix_age <- lm(aug_index ~ age_baseline, data = r00_model_data_p2)
tidy(aix_age)
aix_age <- lm(aug_index ~ age_baseline, data = r00_model_data_p3)
tidy(aix_age)
aix_age <- lm(aug_index ~ age_baseline, data = r00_model_data_p4)
tidy(aix_age)
aix_age <- lm(aug_index ~ age_baseline, data = r00_model_data_p5)
tidy(aix_age)
aix_age <- lm(aug_index ~ age_baseline, data = r00_model_data_p6)
tidy(aix_age)

aix_bmi <- lm(aug_index ~ bmi, data = r00_model_data_baseline)
tidy(aix_bmi)
aix_bmi <- lm(aug_index ~ bmi, data = r00_model_data_p2)
tidy(aix_bmi)
aix_bmi <- lm(aug_index ~ bmi, data = r00_model_data_p3)
tidy(aix_bmi)
aix_bmi <- lm(aug_index ~ bmi, data = r00_model_data_p4)
tidy(aix_bmi)
aix_bmi <- lm(aug_index ~ bmi, data = r00_model_data_p5)
tidy(aix_bmi)
aix_bmi <- lm(aug_index ~ bmi, data = r00_model_data_p6)
tidy(aix_bmi)
```


```{r}
# Run ITT models for AIx

##### AIx ITT primary model - spline with 6 df
# run and save model
model_itt <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) + 
                  (1 | house_id), r00_model_data)

## 2 methods to calculate ICC for models
# ICC using sjstats package
#icc(model_itt)
# ICC using rptR package
#rptGaussian(aug_index ~ (1 | house_id), 
 #           grname = "house_id", data = r00_model_data)
#icc_model <- lmer(as.numeric(mean_temp) ~ (1 | house_id), r00_model_data)
#icc(icc_model)

# summary(model_itt)
# format model output for plotting
tidy_model_itt <- tidy(model_itt, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "all data, primary", "na")) 

############################################################
##### AIx ITT model - participants who completed all 6 phases
model_6phases <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) +
                      (1 | house_id), r00_data_6phases)
# summary(model_6phases)
tidy_model_6phases <- tidy(model_6phases, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "complete case", "na")) 

############################################################
##### AIx ITT model - participants who missed a visit
model_5phases <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) +
                      (1 | house_id), r00_data_5phases)
# summary(model_5phases)
tidy_model_5phases <- tidy(model_5phases, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "missed visit", "na")) 

############################################################
##### AIx ITT model - participants who missed visit 2 - sphygmo malfunction filtered out
model_p2_sphygmo <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) +
                      (1 | house_id), r00_data_sphygmo_p2)
# summary(model_p2_sphygmo)
tidy_model_p2_sphygmo <- tidy(model_p2_sphygmo, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "missed visit 2", "na")) 

############################################################
##### AIx ITT model - spline with 12 df
model_itt_12df <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=12) + 
                  (1 | house_id), r00_model_data)
#summary(model_itt_12df)
tidy_model_12df <- tidy(model_itt_12df, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "spline 12 df", "na")) 

############################################################
##### AIx ITT model - bp meds removed (57 obs)
model_no_bp_meds <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) + 
                         (1 | house_id), r00_model_data_meds)
#summary(model_no_bp_meds)
tidy_model_no_bp_meds <- tidy(model_no_bp_meds, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "no bp meds", "na")) 

############################################################
##### AIx ITT model - visit instead of spline
model_phase <- lmer(aug_index ~ assigned_stove + phase + 
                    (1 | house_id), r00_model_data)
#summary(model_phase)
tidy_model_phase <- tidy(model_phase, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "visit", "na")) 

############################################################
##### AIx ITT model - season instead of spline
model_season <- lmer(aug_index ~ assigned_stove + season + 
                     (1 | house_id), r00_model_data)
#summary(model_season)
tidy_model_season <- tidy(model_season, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "season", "na")) 

############################################################
##### AIx ITT model - with potential ambient confounders
# Try: temp_c, temp_rolling_24, temp_max_previous, temp_max, kitchen_temp,
# ambient_pm, ambient_bc, ambient_oc
model_ambient <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) + 
                      temp_c + log(ambient_bc) +
                      (1 | house_id), r00_model_data)
#summary(model_ambient)
tidy_model_ambient <- tidy(model_ambient, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "ambient", "na"))

############################################################
##### AIx ITT model - with potential confounders based on simple associations with AIx
model_confounders <- lmer(aug_index ~ assigned_stove + ns(date_sphygmo, df=6) + 
                     age_baseline + waist_cat + school_bi +
                     bmi + SES_weighted_sum + whr_cat + phys_act + salt_cat + sugar_cat +
                     (1 | house_id), r00_model_data)
#summary(model_confounders)
tidy_model_confounders <- tidy(model_confounders, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "confounders", "na"))

############################################################
# Combine prepped data for plotting
aix_results <- rbind(tidy_model_itt,
                     tidy_model_6phases,
                     tidy_model_5phases,
                     tidy_model_p2_sphygmo,
                     tidy_model_no_bp_meds,
                     tidy_model_phase,
                     tidy_model_season,
                     tidy_model_12df,
                     tidy_model_ambient,
                     tidy_model_confounders)
#kable(aix_results)
```


```{r}
# Plot model results 

plot_estimates <- aix_results %>%
  mutate(model = factor(model, levels = c("all data, primary", "complete case", "missed visit",
                                          "missed visit 2", "no bp meds", "visit", 
                                          "season", "spline 12 df", "ambient",
                                          "confounders"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  ggtitle(label = "AIx intent-to-treat model") +
  labs(y = "Justa vs traditional (%)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = .8, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-4, -3, -2, -1, 0, 1, 2, 3, 4), 
                     labels = c(-4, -3, -2, -1, 0, 1, 2, 3, 4)) 
plot_estimates
```


\pagebreak  


```{r}
# AIx ITT primary model diagnostic plots

plot(model_itt, main = "AIx primary model", 
     xlab = "fitted values", ylab = "residuals")

qqnorm(residuals(model_itt), main = "AIx primary model QQ Plot")

#aix_influential <- influence(sphygmo_model_season, obs = TRUE)

#aix_cooks <- cooks.distance.estex(aix_influential, sort = TRUE)

#plot.estex(aix_influential, which = "cook")
```

\pagebreak  

```{r, eval=FALSE}
# Simple linear models between CPP and age/bmi
cpp_age <- lm(pulse_pressure_central ~ age_baseline, data = r00_model_data_baseline)
tidy(cpp_age)

cpp_bmi <- lm(pulse_pressure_central ~ bmi, data = r00_model_data_baseline)
tidy(cpp_bmi)
```


```{r}
# Run ITT models for CPP

##### CPP ITT primary model - spline with 6 df
model_itt <- lmer(pulse_pressure_central ~ assigned_stove + ns(date_sphygmo, df=6) + 
                  (1 | house_id), r00_model_data)
#icc(model_itt)

#summary(model_itt)
tidy_model_itt <- tidy(model_itt, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "all data, primary", "na")) 

############################################################
##### CPP ITT model - participants who completed all 6 phases
model_6phases <- lmer(pulse_pressure_central ~ assigned_stove + ns(date_sphygmo, df=6) +
                      (1 | house_id), r00_data_6phases)
# summary(model_6phases)
tidy_model_6phases <- tidy(model_6phases, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "complete case", "na")) 

############################################################
##### CPP ITT model - participants who missed a visit
model_5phases <- lmer(pulse_pressure_central ~ assigned_stove + ns(date_sphygmo, df=6) +
                      (1 | house_id), r00_data_5phases)
# summary(model_5phases)
tidy_model_5phases <- tidy(model_5phases, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "missed visit", "na")) 

############################################################
##### CPP ITT model - participants who missed visit 2 - sphygmo malfunction filtered out
model_p2_sphygmo <- lmer(pulse_pressure_central ~ assigned_stove + ns(date_sphygmo, df=6) +
                      (1 | house_id), r00_data_sphygmo_p2)
# summary(model_p2_sphygmo)
tidy_model_p2_sphygmo <- tidy(model_p2_sphygmo, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "missed visit 2", "na")) 

############################################################
##### CPP ITT model - spline with 12 df
model_itt_12df <- lmer(pulse_pressure_central ~ assigned_stove + ns(date_sphygmo, df=12) + 
                  (1 | house_id), r00_model_data)
#summary(model_itt_12df)
tidy_model_12df <- tidy(model_itt_12df, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "spline 12 df", "na")) 

############################################################
##### CPP ITT model - bp meds removed (57 obs)
model_no_bp_meds <- lmer(pulse_pressure_central ~ assigned_stove + ns(date_sphygmo, df=6) + 
                         (1 | house_id), r00_model_data_meds)
#summary(model_no_bp_meds)
tidy_model_no_bp_meds <- tidy(model_no_bp_meds, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "no bp meds", "na")) 

############################################################
##### CPP ITT model - phase instead of spline
model_phase <- lmer(pulse_pressure_central ~ assigned_stove + phase + 
                    (1 | house_id), r00_model_data)
#summary(model_phase)
tidy_model_phase <- tidy(model_phase, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "visit", "na")) 

############################################################
##### CPP ITT model - season instead of spline
model_season <- lmer(pulse_pressure_central ~ assigned_stove + season + 
                     (1 | house_id), r00_model_data)
#summary(model_season)
tidy_model_season <- tidy(model_season, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "season", "na")) 

############################################################
##### CPP ITT model - with potential ambient confounders
# Try: temp_c, temp_rolling_24, temp_max_previous, temp_max, kitchen_temp,
# ambient_pm, ambient_bc, ambient_oc
model_ambient <- lmer(pulse_pressure_central ~ assigned_stove + 
                      ns(date_sphygmo, df=6) + 
                      temp_c + log(ambient_bc) +
                      (1 | house_id), r00_model_data)
#summary(model_ambient)
tidy_model_ambient <- tidy(model_ambient, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "ambient", "na"))

############################################################
##### CPP ITT model - with potential confounders based on simple associations with AIx
model_confounders <- lmer(pulse_pressure_central ~ assigned_stove + 
                     ns(date_sphygmo, df=6) + age_baseline + waist_cat + school_bi +
                     bmi + SES_weighted_sum + whr_cat + phys_act + 
                     (1 | house_id), r00_model_data)
#summary(model_confounders)
tidy_model_confounders <- tidy(model_confounders, conf.int = TRUE) %>% 
    filter(grepl('assigned_stoveJusta', term)) %>% 
    mutate(model = if_else(term == "assigned_stoveJusta", "confounders", "na"))

############################################################
# Combine prepped data for plotting
cpp_results <- rbind(tidy_model_itt,
                     tidy_model_6phases,
                     tidy_model_5phases,
                     tidy_model_p2_sphygmo,
                     tidy_model_no_bp_meds,
                     tidy_model_phase,
                     tidy_model_season,
                     tidy_model_12df,
                     tidy_model_confounders)
#kable(cpp_results)
```


```{r}
# Plot CPP results

plot_estimates <- cpp_results %>%
  mutate(model = factor(model, levels = c("all data, primary", "complete case", "missed visit",
                                          "missed visit 2", "no bp meds", 
                                          "visit", "season", "spline 12 df",
                                          "confounders"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  ggtitle(label = "CPP intent-to-treat model") +
  labs(y = "Justa vs traditional (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = .8, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-3, -2, -1, 0, 1, 2, 3), 
                     labels = c(-3, -2, -1, 0, 1, 2, 3)) 
plot_estimates
```

\pagebreak  

# Central Pulse Pressure primary model diagnostic plots
# Log transformed CPP helps diagnostic plots, but makes no difference in results
## Continuing to use untransformed CPP in primary analyses for ease of interpretation
```{r}
plot(model_itt, main = "Central Pulse Pressure primary model", 
     xlab = "fitted values", ylab = "residuals")

qqnorm(residuals(model_itt), main = "Central Pulse Pressure primary model QQ Plot")


#cpp_influential <- influence(sphygmo_model_season, obs = TRUE)

#cpp_cooks <- cooks.distance.estex(aix_influential, sort = TRUE)

#plot.estex(cpp_influential, which = "cook")
```

