---
title: "Honduras R00 BP PM Models and Plots"
author: "Ethan Walker"
date: "Updated 22 Oct 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      fig.width = 8, fig.height = 5)
```


```{r, include=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(broom.mixed)
library(purrr)
library(car)
library(forcats)
library(readxl)
library(naniar)
library(splines)
library(lubridate)
library(knitr)
library(influence.ME)
library(boxcoxmix)
library(gamm4)
library(sjstats)
jvPalette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

# Exposure-response models

```{r}
# Creating datasets for various analyses
## Analyses for outcomes: sys_bp_periph, dia_bp_periph
# load full dataset
#r00_full_long <- read_rds("output/r00_full_repeated_by_phase_5may2020.rds")

r00_full_long <- read_csv("input/r00_full_dataset_28July2021_jpk.csv")

#load dataset with AIx/CPP outliers removed (10 total)
# r00_model_data_outliers_removed <- read_rds("output/r00_model_data_outliers_removed.RDS")

r00_model_data <- r00_full_long %>% 
  mutate(kitchen_temp = as.numeric(mean_temp)) %>%
  # removes 6 observations for participant who wasn't assigned to a study arm
  filter(!is.na(study_arm)) %>% 
  #filter(personal_takeoff == 1) %>% 
  ########### change outcome to health measure of interest ######################
  ######### sys_bp_periph, dia_bp_periph
  mutate(outcome = dia_bp_periph) 
  #group_by(house_id, assigned_stove) %>% 
  #mutate(outcome = mean(outcome, na.rm = T)) %>% 
  #distinct(house_id, assigned_stove, .keep_all = T)
  # further removes 190 observations (n=1168)
  #filter(!is.na(outcome))

r00_model_data <- r00_full_long %>% 
  mutate(kitchen_temp = as.numeric(mean_temp)) %>%
  # removes 6 observations for participant who wasn't assigned to a study arm
  filter(!is.na(study_arm)) %>% 
  mutate(aug_index = if_else(aug_index > 75 | aug_index < -25, 9999, aug_index)) %>% 
  mutate(pulse_pressure_central = if_else(pulse_pressure_central > 75,
                                          9999, pulse_pressure_central)) %>% 
  replace_with_na(replace = list(aug_index = 9999)) %>% 
  replace_with_na(replace = list(pulse_pressure_central = 9999)) %>% 
  ########### change outcome to health measure of interest ######################
  ######### aug_index, pulse_pressure_central
  mutate(outcome = pulse_pressure_central) 
  

# Dataset for participants who have BP data for all 6 Phases (113 participants, 678 obs)
r00_data_6phases <- r00_model_data %>%
  filter(complete_case_sbp == 1) 
  
# Dataset for participants who have BP data for <6 Phases (118 participants, 493 obs)
r00_data_5phases <- r00_model_data %>%
  filter(complete_case_sbp == 0) 


# Dataset removing 46 participants who missed BP in phase 2 from sphygmo malfunction
r00_data_sphygmo_p2 <- r00_model_data %>%
  # removes 6 observations for participant who wasn't assigned to a study arm
  filter(!is.na(study_arm)) %>% 
  mutate(sphygmo_missing_phase2 = as.numeric(sys_bp_final_nurse),
         sphygmo_missing_phase2 = if_else(sphygmo_missing_phase2 > 1, 1, 0),
         sphygmo_missing_phase2 = if_else(is.na(sphygmo_missing_phase2),
                                          0, sphygmo_missing_phase2)) %>%
  group_by(house_id) %>%
  filter(sum(sphygmo_missing_phase2) == 0) %>% 
  ungroup() %>%
  filter(!is.na(outcome))  # 955 obs from 184 participants   


# Filtering out medication users (n=59 obs)
r00_model_data_meds <- r00_model_data %>% 
  #filtering out bp med users
  filter(is.na(med_bp)) 


# Filter data for each phase/visit and season
phase_1 <- r00_model_data %>% 
  filter(phase == 1)
phase_2 <- r00_model_data %>% 
  filter(phase == 2)
phase_3 <- r00_model_data %>% 
  filter(phase == 3)
phase_4 <- r00_model_data %>% 
  filter(phase == 4)
phase_5 <- r00_model_data %>% 
  filter(phase == 5)
phase_6 <- r00_model_data %>% 
  filter(phase == 6)

season_rainy <- r00_model_data %>% 
  filter(season == 1)
season_dry <- r00_model_data %>% 
  filter(season == 2)
```


```{r}
# Kitchen PM

##### Kitchen PM all data
model_apm <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)
# summary(model_apm)
tidy_model_apm <- tidy(model_apm, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "all data, primary", "na")) 
nobs(model_apm)

############################################################
##### Kitchen PM initial model - no time
model_apm_no_time <- lmer(outcome ~ log_a_twa + age_baseline +
                         waist_cm + school_bi + (1 | house_id), 
                         r00_model_data)
#summary(model_apm_no_time)

write_rds(model_apm_no_time, "output/kpm_sbp.rds")
write_rds(model_apm_no_time, "output/kpm_dbp.rds")
write_rds(model_apm_no_time, "output/kpm_aix.rds")
write_rds(model_apm_no_time, "output/kpm_cpp.rds")

tidy_model_apm_no_time <- tidy(model_apm_no_time, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "no time", "na"))
nobs(model_apm_no_time)

############################################################
##### LTA Kitchen PM
model_apm_lta <- lmer(outcome ~ pred_log_a_twa_LTA + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)
#summary(model_ppm_lta)

write_rds(model_apm_lta, "output/kpm_lta_sbp.rds")
write_rds(model_apm_lta, "output/kpm_lta_dbp.rds")
write_rds(model_apm_lta, "output/kpm_lta_aix.rds")
write_rds(model_apm_lta, "output/kpm_lta_cpp.rds")

tidy_model_apm_lta <- tidy(model_apm_lta, conf.int = TRUE) %>% 
    filter(grepl('pred_log_a_twa_LTA', term)) %>% 
    mutate(model = if_else(term == "pred_log_a_twa_LTA", "all data, primary", "na")) 
nobs(model_apm_lta)

############################################################
##### ITT model - using joined bp data (sphygmo and manual during visit 2)
model_apm_bpjoined <- lmer(dia_bp_joined ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)
# summary(model_apm_bpjoined)
tidy_model_apm_bpjoined <- tidy(model_apm_bpjoined, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "bp joined", "na")) 

############################################################
##### Kitchen PM complete case
model_apm_6phases <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + (1 | house_id), r00_data_6phases)
#summary(model_apm_6phases)
tidy_model_apm_6phases <- tidy(model_apm_6phases, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "complete case", "na")) 

############################################################
##### Kitchen PM missed visit
model_apm_5phases <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + (1 | house_id), r00_data_5phases)
#summary(model_apm_5phases)
tidy_model_apm_5phases <- tidy(model_apm_5phases, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "missed visit", "na")) 

############################################################
##### Kitchen PM - participants who missed visit 2 - sphygmo malfunction filtered out
model_p2_sphygmo <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) +
                           age_baseline + waist_cm + school_bi +
                      (1 | house_id), r00_data_sphygmo_p2)
# summary(model_p2_sphygmo)
tidy_model_p2_sphygmo <- tidy(model_p2_sphygmo, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "missed visit 2", "na")) 

############################################################
##### Kitchen PM initial model - bp meds removed (59 obs)
model_apm_no_bp_meds <- lmer(outcome ~ log_a_twa + 
                             ns(date_sphygmo, df=6) + age_baseline +
                             waist_cm + school_bi + (1 | house_id), 
                             r00_model_data_meds)
#summary(model_apm_no_bp_meds)
tidy_model_apm_no_bp_meds <- tidy(model_apm_no_bp_meds, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "no bp meds", "na")) 

############################################################
##### Kitchen PM initial model - dichotomous confounders
model_apm_di_conf <- lmer(outcome ~ log_a_twa + 
                          ns(date_sphygmo, df=6) + age_cat_40 +
                          waist_cat + school_bi + (1 | house_id), 
                          r00_model_data)
#summary(model_apm_di_conf)
tidy_model_apm_di_conf <- tidy(model_apm_di_conf, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "di confdrs", "na"))

############################################################
##### Kitchen PM initial model - date spline with 12 df
model_apm_spline12 <- lmer(outcome ~ log_a_twa + 
                           ns(date_sphygmo, df=12) + age_baseline +
                           waist_cm + school_bi + (1 | house_id), 
                           r00_model_data)
#summary(model_apm_spline12)
tidy_model_apm_spline12 <- tidy(model_apm_spline12, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "spline 12 df", "na")) 

############################################################
##### Kitchen PM initial model - date spline with 3 df
model_apm_spline3 <- lmer(outcome ~ log_a_twa + 
                           ns(date_sphygmo, df=3) + age_baseline +
                           waist_cm + school_bi + (1 | house_id), 
                           r00_model_data)
#summary(model_apm_spline3)
tidy_model_apm_spline3 <- tidy(model_apm_spline3, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "spline 3 df", "na"))

############################################################
##### Kitchen PM reduced model 
model_apm_reduced <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) +
                         (1 | house_id), r00_model_data)
#summary(model_apm_reduced)
tidy_model_apm_reduced <- tidy(model_apm_reduced, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "reduced", "na")) 

############################################################
##### Kitchen PM initial model - visit instead of spline
model_apm_phase <- lmer(outcome ~ log_a_twa + phase + age_baseline + 
                        waist_cm + school_bi + (1 | house_id), r00_model_data)
#summary(model_apm_phase)
tidy_model_apm_phase <- tidy(model_apm_phase, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit", "na"))

############################################################
##### Kitchen PM initial model - season instead of spline
model_apm_season <- lmer(outcome ~ log_a_twa + season + age_baseline +
                         waist_cm + school_bi + (1 | house_id), r00_model_data)
#summary(model_apm_season)
tidy_model_apm_season <- tidy(model_apm_season, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "season", "na"))

############################################################
##### Kitchen PM initial model - no time variable
model_apm_no_time <- lmer(outcome ~ log_a_twa + age_baseline +
                         waist_cm + school_bi + (1 | house_id), r00_model_data)
#summary(model_apm_no_time)
tidy_model_apm_no_time <- tidy(model_apm_no_time, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "no time", "na"))

############################################################
##### Kitchen PM initial model - bmi instead of waist_cm
model_apm_bmi <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                      bmi + school_bi + (1 | house_id), r00_model_data)
#summary(model_apm_bmi)
tidy_model_apm_bmi <- tidy(model_apm_bmi, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "bmi", "na"))

############################################################
##### Kitchen PM initial model - whr instead of waist_cm
model_apm_whr <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                      whr + school_bi + (1 | house_id), r00_model_data)
#summary(model_apm_whr)
tidy_model_apm_whr <- tidy(model_apm_whr, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "whr", "na"))

############################################################
##### Kitchen PM initial model - adding beds_new
model_apm_beds <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + beds_new + (1 | house_id), 
                       r00_model_data)
#summary(model_apm_beds)
tidy_model_apm_beds <- tidy(model_apm_beds, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "beds", "na"))

############################################################
##### Kitchen PM initial model - adding ses_materials
model_apm_ses <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + ses_materials + (1 | house_id),
                      r00_model_data)
#summary(model_apm_ses)
tidy_model_apm_ses <- tidy(model_apm_ses, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "ses assets", "na"))

############################################################
##### Kitchen PM initial model - adding phys_act
model_apm_pa <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                     waist_cm + school_bi + phys_act + (1 | house_id), 
                     r00_model_data)
#summary(model_apm_pa)
tidy_model_apm_pa <- tidy(model_apm_pa, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "phys act", "na"))

############################################################
##### Kitchen PM initial model - adding dds_total
model_apm_dds <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + dds_total + (1 | house_id), 
                      r00_model_data)
#summary(model_apm_dds)
tidy_model_apm_dds <- tidy(model_apm_dds, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "dds", "na"))

############################################################
##### Kitchen PM initial model - model with kitchen or ambient temp
# Try: temp_c, temp_rolling_24, temp_max_previous, temp_max, kitchen_temp,
# ambient_pm, ambient_bc, ambient_oc
model_apm_ambient <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + temp_c + 
                       (1 | house_id), r00_model_data)
#summary(model_apm_ambient)
tidy_model_apm_ambient <- tidy(model_apm_ambient, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "ambient", "na"))

############################################################
##### Kitchen PM initial model - full model with all potential confounders
model_apm_confounders <- lmer(outcome ~ log_a_twa + ns(date_sphygmo, df=6) + 
                          age_baseline + waist_cm + school_bi + 
                          SES_weighted_sum + dds_cat + bmi + phys_act + salt_cat +
                          (1 | house_id), r00_model_data)
#summary(model_apm_confounders)
tidy_model_apm_confounders <- tidy(model_apm_confounders, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    mutate(model = if_else(term == "log_a_twa", "confounders", "na"))

############################################################
##### Kitchen PM models by individual phase/visit and season
model_p1 <- lm(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi , phase_1)
# summary(model_p1)
tidy_model_p1 <- tidy(model_p1, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>% 
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit 1", "na"))

model_p2 <- lm(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi , phase_2)
# summary(model_p2)
tidy_model_p2 <- tidy(model_p2, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit 2", "na"))

model_p3 <- lm(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi , phase_3)
# summary(model_p3)
tidy_model_p3 <- tidy(model_p3, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit 3", "na"))

model_p4 <- lm(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi , phase_4)
# summary(model_p4)
tidy_model_p4 <- tidy(model_p4, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit 4", "na"))

model_p5 <- lm(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi , phase_5)
# summary(model_p5)
tidy_model_p5 <- tidy(model_p5, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit 5", "na"))

model_p6 <- lm(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi , phase_6)
# summary(model_p6)
tidy_model_p6 <- tidy(model_p6, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_a_twa", "visit 6", "na"))




model_rainy <- lmer(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi +
                   ns(date_sphygmo, df=3) + (1 | house_id), season_rainy)
#summary(model_rainy)
tidy_model_rainy <- tidy(model_rainy, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value, -effect, -group, -df) %>% 
    mutate(model = if_else(term == "log_a_twa", "rainy season", "na"))

model_dry <- lmer(outcome ~ log_a_twa + 
                   age_baseline + waist_cm + school_bi +
                   ns(date_sphygmo, df=3) + (1 | house_id), season_dry)
#summary(model_dry)
tidy_model_dry <- tidy(model_dry, conf.int = TRUE) %>% 
    filter(grepl('log_a_twa', term)) %>%  
    select(-p.value, -effect, -group, -df) %>% 
    mutate(model = if_else(term == "log_a_twa", "dry season", "na"))


############################################################
# Combine formatted results for plotting
results_time <- rbind(tidy_model_apm_no_time,
                      tidy_model_apm_season,
                      tidy_model_apm_phase,
                      tidy_model_apm)


results <- rbind(tidy_model_apm,
                     tidy_model_apm_bpjoined,
                     tidy_model_apm_6phases,
                     tidy_model_apm_5phases,
                     tidy_model_p2_sphygmo,
                     tidy_model_apm_no_bp_meds,
                     tidy_model_apm_spline12,
                     tidy_model_apm_spline3,
                     tidy_model_apm_ambient,
                     tidy_model_apm_confounders)


results_phase_season <- rbind(tidy_model_p1,
                              tidy_model_p2,
                              tidy_model_p3,
                              tidy_model_p4,
                              tidy_model_p5,
                              tidy_model_p6,
                              tidy_model_rainy,
                              tidy_model_dry)
#kable(results)
```



```{r}
## Plot model estimates - Kitchen PM

plot_estimates <- results_time %>%
  mutate(model = factor(model, levels = c("no time", "season",
                                          "visit", "primary"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9, 4, 8, 14, 10, 12, 7, 11)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  ggtitle(label = "Diastolic BP - Kitchen PM model") +
  labs(y = "Estimate per natural log increase \n in fine particulate matter (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1), 
                     labels = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1)) 
#plot_estimates


plot_estimates <- results %>%
  mutate(model = factor(model, levels = c("all data, primary", "bp joined",
                                          "complete case", "missed visit", "missed visit 2",
                                          "no bp meds", "spline 12 df", "spline 3 df",
                                          "ambient", "confounders"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9, 4, 8, 14, 10, 12, 7, 11)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "Systolic BP - Kitchen PM model") +
  labs(y = "Estimate per natural log increase \n in fine particulate matter (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1), 
                     labels = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1)) 
plot_estimates


plot_estimates <- results_phase_season %>%
  mutate(model = factor(model, levels = c("visit 1", "visit 2",
                                          "visit 3", "visit 4",
                                          "visit 5", "visit 6", 
                                          "rainy season", "dry season"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9, 4, 8, 14, 10, 12, 7, 11)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "Systolic BP - Kitchen PM model") +
  labs(y = "Estimate per natural log increase \n in fine particulate matter (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-4, -3, -2, -1, 0, 1, 2, 3, 4), 
                     labels = c(-4, -3, -2, -1, 0, 1, 2, 3, 4)) 
plot_estimates
```


```{r}
# Primary model diagnostic plots - Kitchen PM

plot(model_apm, main = "Kitchen PM primary model", 
     xlab = "fitted values", ylab = "residuals")

qqnorm(residuals(model_apm), main = "Kitchen PM primary model")


#influential <- influence(model_apm, obs = TRUE)

#cooks <- cooks.distance.estex(influential, sort = TRUE)

#plot.estex(influential, which = "cook")
```

---------------------------------


```{r}
# Personal PM

##### personal PM all data
model_ppm <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)
# summary(model_ppm)
tidy_model_ppm <- tidy(model_ppm, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "all data, primary", "na")) 
nobs(model_ppm)

############################################################
##### personal PM initial model - no time
model_ppm_no_time <- lmer(outcome ~ log_p_twa + age_baseline +
                         waist_cm + school_bi + (1 | house_id), 
                         r00_model_data)

write_rds(model_ppm_no_time, "output/ppm_sbp.rds")
write_rds(model_ppm_no_time, "output/ppm_dbp.rds")
write_rds(model_ppm_no_time, "output/ppm_aix.rds")
write_rds(model_ppm_no_time, "output/ppm_cpp.rds")

#summary(model_ppm_no_time)
tidy_model_ppm_no_time <- tidy(model_ppm_no_time, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "no time", "na"))
nobs(model_ppm_no_time)

############################################################
##### LTA personal PM
model_ppm_lta <- lmer(outcome ~ pred_log_p_twa_LTA + age_baseline + 
                    waist_cm + school_bi + (1 | house_id), r00_model_data)

write_rds(model_ppm_lta, "output/ppm_lta_sbp.rds")
write_rds(model_ppm_lta, "output/ppm_lta_dbp.rds")
write_rds(model_ppm_lta, "output/ppm_lta_aix.rds")
write_rds(model_ppm_lta, "output/ppm_lta_cpp.rds")

#summary(model_ppm_lta)
tidy_model_ppm_lta <- tidy(model_ppm_lta, conf.int = TRUE) %>% 
    filter(grepl('pred_log_p_twa_LTA', term)) %>% 
    mutate(model = if_else(term == "pred_log_p_twa_LTA", "all data, primary", "na")) 
nobs(model_ppm_lta)

############################################################
##### ITT model - using joined bp data (sphygmo and manual during visit 2)
model_ppm_bpjoined <- lmer(dia_bp_joined ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)
# summary(model_ppm_bpjoined)
tidy_model_ppm_bpjoined <- tidy(model_ppm_bpjoined, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "bp joined", "na")) 

############################################################
##### personal PM complete case
model_ppm_6phases <- lmer(outcome ~ log_p_twa + 
                            ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + (1 | house_id), r00_data_6phases)
#summary(model_ppm_6phases)
tidy_model_ppm_6phases <- tidy(model_ppm_6phases, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "complete case", "na")) 

############################################################
##### personal PM missed phase
model_ppm_5phases <- lmer(outcome ~ log_p_twa + 
                            ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + (1 | house_id), r00_data_5phases)
#summary(model_ppm_5phases)
tidy_model_ppm_5phases <- tidy(model_ppm_5phases, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "missed visit", "na"))

############################################################
##### personal PM - participants who missed phase 2 - sphygmo malfunction filtered out
model_p2_sphygmo <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) +
                           age_baseline + waist_cm + school_bi +
                      (1 | house_id), r00_data_sphygmo_p2)
# summary(model_p2_sphygmo)
tidy_model_p2_sphygmo <- tidy(model_p2_sphygmo, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "missed visit 2", "na")) 

############################################################
##### personal PM initial model - bp meds removed (57 obs)
model_ppm_no_bp_meds <- lmer(outcome ~ log_p_twa + 
                             ns(date_sphygmo, df=6) + age_baseline +
                             waist_cm + school_bi + (1 | house_id), 
                             r00_model_data_meds)
#summary(model_ppm_no_bp_meds)
tidy_model_ppm_no_bp_meds <- tidy(model_ppm_no_bp_meds, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "no bp meds", "na")) 

############################################################
##### personal PM initial model - dichotomous confounders
model_ppm_di_conf <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_cat_40 +
                          waist_cat + school_bi + (1 | house_id), r00_model_data)
#summary(model_ppm_di_conf)
tidy_model_ppm_di_conf <- tidy(model_ppm_di_conf, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "di confdrs", "na"))

############################################################
##### personal PM initial model - spline with 12 df
model_ppm_spline12 <- lmer(outcome ~ log_p_twa + 
                           ns(date_sphygmo, df=12) + age_baseline +
                           waist_cm + school_bi + (1 | house_id), 
                           r00_model_data)
#summary(model_ppm_spline12)
tidy_model_ppm_spline12 <- tidy(model_ppm_spline12, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "spline 12 df", "na")) 

############################################################
##### personal PM initial model - spline with 3 df
model_ppm_spline3 <- lmer(outcome ~ log_p_twa + 
                           ns(date_sphygmo, df=3) + age_baseline +
                           waist_cm + school_bi + (1 | house_id), 
                           r00_model_data)
#summary(model_ppm_spline3)
tidy_model_ppm_spline3 <- tidy(model_ppm_spline3, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "spline 3 df", "na")) 

############################################################
##### personal PM reduced model 
model_ppm_reduced <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) +
                         (1 | house_id), r00_model_data)
#summary(model_ppm_reduced)
tidy_model_ppm_reduced <- tidy(model_ppm_reduced, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "reduced", "na")) 

############################################################
##### personal PM initial model - phase instead of spline
model_ppm_phase <- lmer(outcome ~ log_p_twa + phase + age_baseline + 
                        waist_cm + school_bi + (1 | house_id), 
                        r00_model_data)
#summary(model_ppm_phase)
tidy_model_ppm_phase <- tidy(model_ppm_phase, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit", "na"))

############################################################
##### personal PM initial model - season instead of spline
model_ppm_season <- lmer(outcome ~ log_p_twa + season + age_baseline +
                         waist_cm + school_bi + (1 | house_id), 
                         r00_model_data)
#summary(model_ppm_season)
tidy_model_ppm_season <- tidy(model_ppm_season, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "season", "na"))

############################################################
##### personal PM initial model - bmi instead of waist_cm
model_ppm_bmi <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                      bmi + school_bi + (1 | house_id), r00_model_data)
#summary(model_ppm_bmi)
tidy_model_ppm_bmi <- tidy(model_ppm_bmi, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "bmi", "na"))

############################################################
##### personal PM initial model - whr instead of waist_cm
model_ppm_whr <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                      whr + school_bi + (1 | house_id), r00_model_data)
#summary(model_ppm_whr)
tidy_model_ppm_whr <- tidy(model_ppm_whr, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "whr", "na"))

############################################################
##### personal PM initial model - adding beds_new
model_ppm_beds <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + beds_new + (1 | house_id), 
                       r00_model_data)
#summary(model_ppm_beds)
tidy_model_ppm_beds <- tidy(model_ppm_beds, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "beds", "na"))

############################################################
##### personal PM initial model - adding ses_materials
model_ppm_ses <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + ses_materials + (1 | house_id), 
                      r00_model_data)
#summary(model_ppm_ses)
tidy_model_ppm_ses <- tidy(model_ppm_ses, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "ses assets", "na"))

############################################################
##### personal PM initial model - adding phys_act
model_ppm_pa <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                     waist_cm + school_bi + phys_act + (1 | house_id), 
                     r00_model_data)
#summary(model_ppm_pa)
tidy_model_ppm_pa <- tidy(model_ppm_pa, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "phys act", "na"))

############################################################
##### personal PM initial model - adding dds_total
model_ppm_dds <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + dds_total + (1 | house_id), 
                      r00_model_data)
#summary(model_ppm_dds)
tidy_model_ppm_dds <- tidy(model_ppm_dds, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "dds", "na"))

############################################################
# Try: temp_c, temp_rolling_24, temp_max_previous, temp_max, kitchen_temp,
# ambient_pm, ambient_bc, ambient_oc
model_ppm_ambient <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + temp_c + 
                       (1 | house_id), r00_model_data)
#summary(model_ppm_ambient)
tidy_model_ppm_ambient <- tidy(model_ppm_ambient, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "ambient", "na"))

############################################################
##### Personal PM model with all potential confounders
model_ppm_confounders <- lmer(outcome ~ log_p_twa + ns(date_sphygmo, df=6) + 
                          age_baseline + waist_cm + school_bi + 
                          SES_weighted_sum + dds_cat + bmi + phys_act + salt_cat +
                          (1 | house_id), r00_model_data)
#summary(model_ppm_confounders)
tidy_model_ppm_confounders <- tidy(model_ppm_confounders, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>% 
    mutate(model = if_else(term == "log_p_twa", "confounders", "na"))


############################################################
##### Personal PM models by individual phase/visit and season
model_p1 <- lm(outcome ~ log_p_twa + age_baseline +  
                   waist_cm + school_bi, phase_1)
# summary(model_p1)
tidy_model_p1 <- tidy(model_p1, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit 1", "na"))


model_p2 <- lm(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi , phase_2)
# summary(model_p2)
tidy_model_p2 <- tidy(model_p2, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit 2", "na"))

model_p3 <- lm(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi , phase_3)
# summary(model_p3)
tidy_model_p3 <- tidy(model_p3, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit 3", "na"))

model_p4 <- lm(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi , phase_4)
# summary(model_p4)
tidy_model_p4 <- tidy(model_p4, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit 4", "na"))

model_p5 <- lm(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi , phase_5)
# summary(model_p5)
tidy_model_p5 <- tidy(model_p5, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit 5", "na"))

model_p6 <- lm(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi , phase_6)
# summary(model_p6)
tidy_model_p6 <- tidy(model_p6, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value) %>% 
    mutate(model = if_else(term == "log_p_twa", "visit 6", "na"))




model_rainy <- lmer(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi +
                   ns(date_sphygmo, df=3) + (1 | house_id), season_rainy)
# summary(model_rainy)
tidy_model_rainy <- tidy(model_rainy, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value, -effect, -group, -df) %>%
    mutate(model = if_else(term == "log_p_twa", "rainy season", "na"))

model_dry <- lmer(outcome ~ log_p_twa + 
                   age_baseline + waist_cm + school_bi +
                   ns(date_sphygmo, df=3) + (1 | house_id), season_dry)
# summary(model_dry)
tidy_model_dry <- tidy(model_dry, conf.int = TRUE) %>% 
    filter(grepl('log_p_twa', term)) %>%  
    select(-p.value, -effect, -group, -df) %>%
    mutate(model = if_else(term == "log_p_twa", "dry season", "na"))




############################################################
results_time <- rbind(tidy_model_ppm_no_time,
                      tidy_model_ppm_season,
                      tidy_model_ppm_phase,
                      tidy_model_ppm)


results <- rbind(tidy_model_ppm,
                     tidy_model_ppm_bpjoined,
                     tidy_model_ppm_6phases,
                     tidy_model_ppm_5phases,
                     tidy_model_p2_sphygmo,
                     tidy_model_ppm_no_bp_meds,
                     tidy_model_ppm_spline12,
                     tidy_model_ppm_spline3,
                     tidy_model_ppm_ambient,
                     tidy_model_ppm_confounders)


results_phase_season <- rbind(tidy_model_p1,
                              tidy_model_p2,
                              tidy_model_p3,
                              tidy_model_p4,
                              tidy_model_p5,
                              tidy_model_p6,
                              tidy_model_rainy,
                              tidy_model_dry)
#kable(results)
```


```{r}
## Plot model estimates - Personal PM

plot_estimates <- results_time %>%
  mutate(model = factor(model, levels = c("no time", "season",
                                          "visit", "primary"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9, 4, 8, 14, 10, 12, 7, 11)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  ggtitle(label = "Diastolic BP - Personal PM model") +
  labs(y = "Estimate per natural log increase \n in fine particulate matter (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1), 
                     labels = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1)) 
#plot_estimates


plot_estimates <- results %>%
  mutate(model = factor(model, levels = c("all data, primary", "bp joined",
                                          "complete case", "missed visit", "missed visit 2",
                                          "no bp meds", "spline 12 df", "spline 3 df",
                                          "ambient", "confounders"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9, 4, 8, 14, 10, 12, 7, 11)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "Systolic BP - Personal PM model") +
  labs(y = "Estimate per natural log increase \n in fine particulate matter (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1), 
                     labels = c(-1, -.75, -.5, -.25, 0, .25, .5, .75, 1)) 
plot_estimates


plot_estimates <- results_phase_season %>%
  mutate(model = factor(model, levels = c("visit 1", "visit 2",
                                          "visit 3", "visit 4",
                                          "visit 5", "visit 6", 
                                          "rainy season", "dry season"))) %>% 
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  #scale_shape_manual(values = c(15, 16, 17, 18, 13, 9, 4, 8, 14, 10, 12, 7, 11)) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +  
  #ggtitle(label = "systolic BP - Personal PM model") +
  labs(y = "Estimate per natural log increase \n in fine particulate matter (mmHg)") +
  labs(x = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 16, colour = "black", angle = 25,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 16,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.position = "none") +
  scale_y_continuous(breaks = c(-4, -3, -2, -1, 0, 1, 2, 3, 4), 
                     labels = c(-4, -3, -2, -1, 0, 1, 2, 3, 4)) 
plot_estimates
```


```{r}
# Primary model diagnostic plots - Personal PM

plot(model_ppm, main = "Personal PM primary model", 
     xlab = "fitted values", ylab = "residuals")

qqnorm(residuals(model_ppm), main = "Personal PM primary model")


#influential <- influence(model_ppm, obs = TRUE)

#cooks <- cooks.distance.estex(influential, sort = TRUE)

#plot.estex(influential, which = "cook")
```


```{r}
# Kitchen BC

##### Kitchen BC initial model - no time
model_abc_no_time <- lmer(outcome ~ log_bc_area + age_baseline +
                         waist_cm + school_bi + (1 | house_id), 
                         r00_model_data)

write_rds(model_abc_no_time, "output/kbc_sbp.rds")
write_rds(model_abc_no_time, "output/kbc_dbp.rds")
write_rds(model_abc_no_time, "output/kbc_aix.rds")
write_rds(model_abc_no_time, "output/kbc_cpp.rds")

#summary(model_abc_no_time)
tidy_model_abc_no_time <- tidy(model_abc_no_time, conf.int = TRUE) %>% 
    filter(grepl('log_bc_area', term)) %>% 
    mutate(model = if_else(term == "log_bc_area", "no time", "na"))
nobs(model_abc_no_time)

############################################################
##### LTA Kitchen BC
model_abc_lta <- lmer(outcome ~ pred_log_bc_area_LTA + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)

write_rds(model_abc_lta, "output/kbc_lta_sbp.rds")
write_rds(model_abc_lta, "output/kbc_lta_dbp.rds")
write_rds(model_abc_lta, "output/kbc_lta_aix.rds")
write_rds(model_abc_lta, "output/kbc_lta_cpp.rds")

#summary(model_abc_lta)
tidy_model_abc_lta <- tidy(model_abc_lta, conf.int = TRUE) %>% 
    filter(grepl('pred_log_bc_area_LTA', term)) %>% 
    mutate(model = if_else(term == "pred_log_bc_area_LTA", "all data, primary", "na")) 
nobs(model_abc_lta)

############################################################

```


```{r}
# Personal BC

##### Personal BC initial model - no time
model_pbc_no_time <- lmer(outcome ~ log_bc_personal + age_baseline +
                         waist_cm + school_bi + (1 | house_id), 
                         r00_model_data)

write_rds(model_pbc_no_time, "output/pbc_sbp.rds")
write_rds(model_pbc_no_time, "output/pbc_dbp.rds")
write_rds(model_pbc_no_time, "output/pbc_aix.rds")
write_rds(model_pbc_no_time, "output/pbc_cpp.rds")

#summary(model_pbc_no_time)
tidy_model_pbc_no_time <- tidy(model_pbc_no_time, conf.int = TRUE) %>% 
    filter(grepl('log_bc_personal', term)) %>% 
    mutate(model = if_else(term == "log_bc_personal", "no time", "na"))
nobs(model_pbc_no_time)

############################################################
##### LTA Personal BC
model_pbc_lta <- lmer(outcome ~ pred_log_bc_personal_LTA + age_baseline + 
                      waist_cm + school_bi + (1 | house_id), r00_model_data)

write_rds(model_pbc_lta, "output/pbc_lta_sbp.rds")
write_rds(model_pbc_lta, "output/pbc_lta_dbp.rds")
write_rds(model_pbc_lta, "output/pbc_lta_aix.rds")
write_rds(model_pbc_lta, "output/pbc_lta_cpp.rds")

#summary(model_pbc_lta)
tidy_model_pbc_lta <- tidy(model_pbc_lta, conf.int = TRUE) %>% 
    filter(grepl('pred_log_bc_personal_LTA', term)) %>% 
    mutate(model = if_else(term == "pred_log_bc_personal_LTA", "all data, primary", "na")) 
nobs(model_pbc_lta)

############################################################

```


```{r}
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")

colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                        "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")

# Load results
kpm_sbp <- read_rds("output/kpm_sbp.rds")
kpm_dbp <- read_rds("output/kpm_dbp.rds")
kpm_aix <- read_rds("output/kpm_aix.rds")
kpm_cpp <- read_rds("output/kpm_cpp.rds")

ppm_sbp <- read_rds("output/ppm_sbp.rds")
ppm_dbp <- read_rds("output/ppm_dbp.rds")
ppm_aix <- read_rds("output/ppm_aix.rds")
ppm_cpp <- read_rds("output/ppm_cpp.rds")

kbc_sbp <- read_rds("output/kbc_sbp.rds")
kbc_dbp <- read_rds("output/kbc_dbp.rds")
kbc_aix <- read_rds("output/kbc_aix.rds")
kbc_cpp <- read_rds("output/kbc_cpp.rds")

pbc_sbp <- read_rds("output/pbc_sbp.rds")
pbc_dbp <- read_rds("output/pbc_dbp.rds")
pbc_aix <- read_rds("output/pbc_aix.rds")
pbc_cpp <- read_rds("output/pbc_cpp.rds")

kpm_lta_sbp <- read_rds("output/kpm_lta_sbp.rds")
kpm_lta_dbp <- read_rds("output/kpm_lta_dbp.rds")
kpm_lta_aix <- read_rds("output/kpm_lta_aix.rds")
kpm_lta_cpp <- read_rds("output/kpm_lta_cpp.rds")

ppm_lta_sbp <- read_rds("output/ppm_lta_sbp.rds")
ppm_lta_dbp <- read_rds("output/ppm_lta_dbp.rds")
ppm_lta_aix <- read_rds("output/ppm_lta_aix.rds")
ppm_lta_cpp <- read_rds("output/ppm_lta_cpp.rds")

kbc_lta_sbp <- read_rds("output/kbc_lta_sbp.rds")
kbc_lta_dbp <- read_rds("output/kbc_lta_dbp.rds")
kbc_lta_aix <- read_rds("output/kbc_lta_aix.rds")
kbc_lta_cpp <- read_rds("output/kbc_lta_cpp.rds")

pbc_lta_sbp <- read_rds("output/pbc_lta_sbp.rds")
pbc_lta_dbp <- read_rds("output/pbc_lta_dbp.rds")
pbc_lta_aix <- read_rds("output/pbc_lta_aix.rds")
pbc_lta_cpp <- read_rds("output/pbc_lta_cpp.rds")

# Function to clean results
results_function <- function(model_results, model_name) {
  
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("log", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("log_a_twa", "Kitchen PM", term),
         term = gsub("log_p_twa", "Personal PM", term),
         term = gsub("log_bc_area", "Kitchen BC", term),
         term = gsub("log_bc_personal", "Personal BC", term),
         model = model_name) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(model, term, estimate, p.value, conf.low, conf.high)
tidy_results
}

results_function_lta <- function(model_results, model_name) {
  
tidy_results <- tidy(model_results, conf.int = TRUE) %>% 
  mutate(group_filter = if_else(grepl("log", term), 1, 0)) %>% 
  filter(group_filter == 1) %>% 
  mutate(term = gsub("pred_log_a_twa_LTA", "Kitchen PM, LTA", term),
         term = gsub("pred_log_p_twa_LTA", "Personal PM, LTA", term),
         term = gsub("pred_log_bc_area_LTA", "Kitchen BC, LTA", term),
         term = gsub("pred_log_bc_personal_LTA", "Personal BC, LTA", term),
         model = model_name) %>% 
  mutate(estimate = round(estimate, digits = 2),
         conf.low = round(conf.low, digits = 2),
         conf.high = round(conf.high, digits = 2)) %>% 
  dplyr::select(model, term, estimate, p.value, conf.low, conf.high)
tidy_results
}

kpm_sbp_tidy <- results_function(kpm_sbp, "Systolic BP")
kpm_dbp_tidy <- results_function(kpm_dbp, "Diastolic BP")
kpm_aix_tidy <- results_function(kpm_aix, "Aug Index")
kpm_cpp_tidy <- results_function(kpm_cpp, "Cent Pulse Press")

kpm_combined <- rbind(kpm_sbp_tidy, kpm_dbp_tidy, kpm_aix_tidy, kpm_cpp_tidy)

ppm_sbp_tidy <- results_function(ppm_sbp, "Systolic BP")
ppm_dbp_tidy <- results_function(ppm_dbp, "Diastolic BP")
ppm_aix_tidy <- results_function(ppm_aix, "Aug Index")
ppm_cpp_tidy <- results_function(ppm_cpp, "Cent Pulse Press")

ppm_combined <- rbind(ppm_sbp_tidy, ppm_dbp_tidy, ppm_aix_tidy, ppm_cpp_tidy)

pm_combined <- rbind(kpm_sbp_tidy, kpm_dbp_tidy, kpm_aix_tidy, kpm_cpp_tidy,
                     ppm_sbp_tidy, ppm_dbp_tidy, ppm_aix_tidy, ppm_cpp_tidy)

kbc_sbp_tidy <- results_function(kbc_sbp, "Systolic BP")
kbc_dbp_tidy <- results_function(kbc_dbp, "Diastolic BP")
kbc_aix_tidy <- results_function(kbc_aix, "Aug Index")
kbc_cpp_tidy <- results_function(kbc_cpp, "Cent Pulse Press")

kbc_combined <- rbind(kbc_sbp_tidy, kbc_dbp_tidy, kbc_aix_tidy, kbc_cpp_tidy)

pbc_sbp_tidy <- results_function(pbc_sbp, "Systolic BP")
pbc_dbp_tidy <- results_function(pbc_dbp, "Diastolic BP")
pbc_aix_tidy <- results_function(pbc_aix, "Aug Index")
pbc_cpp_tidy <- results_function(pbc_cpp, "Cent Pulse Press")

pbc_combined <- rbind(pbc_sbp_tidy, pbc_dbp_tidy, pbc_aix_tidy, pbc_cpp_tidy)

bc_combined <- rbind(kbc_sbp_tidy, kbc_dbp_tidy, kbc_aix_tidy, kbc_cpp_tidy,
                     pbc_sbp_tidy, pbc_dbp_tidy, pbc_aix_tidy, pbc_cpp_tidy)


kpm_lta_sbp_tidy <- results_function_lta(kpm_lta_sbp, "Systolic BP")
kpm_lta_dbp_tidy <- results_function_lta(kpm_lta_dbp, "Diastolic BP")
kpm_lta_aix_tidy <- results_function_lta(kpm_lta_aix, "Aug Index")
kpm_lta_cpp_tidy <- results_function_lta(kpm_lta_cpp, "Cent Pulse Press")

kpm_lta_combined <- rbind(kpm_lta_sbp_tidy, kpm_lta_dbp_tidy, 
                          kpm_lta_aix_tidy, kpm_lta_cpp_tidy)

ppm_lta_sbp_tidy <- results_function_lta(ppm_lta_sbp, "Systolic BP")
ppm_lta_dbp_tidy <- results_function_lta(ppm_lta_dbp, "Diastolic BP")
ppm_lta_aix_tidy <- results_function_lta(ppm_lta_aix, "Aug Index")
ppm_lta_cpp_tidy <- results_function_lta(ppm_lta_cpp, "Cent Pulse Press")

ppm_lta_combined <- rbind(ppm_lta_sbp_tidy, ppm_lta_dbp_tidy, 
                          ppm_lta_aix_tidy, ppm_lta_cpp_tidy)

pm_lta_combined <- rbind(kpm_lta_sbp_tidy, kpm_lta_dbp_tidy, 
                         kpm_lta_aix_tidy, kpm_lta_cpp_tidy,
                         ppm_lta_sbp_tidy, ppm_lta_dbp_tidy, 
                         ppm_lta_aix_tidy, ppm_lta_cpp_tidy)

kbc_lta_sbp_tidy <- results_function_lta(kbc_lta_sbp, "Systolic BP")
kbc_lta_dbp_tidy <- results_function_lta(kbc_lta_dbp, "Diastolic BP")
kbc_lta_aix_tidy <- results_function_lta(kbc_lta_aix, "Aug Index")
kbc_lta_cpp_tidy <- results_function_lta(kbc_lta_cpp, "Cent Pulse Press")

kbc_lta_combined <- rbind(kbc_lta_sbp_tidy, kbc_lta_dbp_tidy, 
                          kbc_lta_aix_tidy, kbc_lta_cpp_tidy)

pbc_lta_sbp_tidy <- results_function_lta(pbc_lta_sbp, "Systolic BP")
pbc_lta_dbp_tidy <- results_function_lta(pbc_lta_dbp, "Diastolic BP")
pbc_lta_aix_tidy <- results_function_lta(pbc_lta_aix, "Aug Index")
pbc_lta_cpp_tidy <- results_function_lta(pbc_lta_cpp, "Cent Pulse Press")

pbc_lta_combined <- rbind(pbc_lta_sbp_tidy, pbc_lta_dbp_tidy, 
                          pbc_lta_aix_tidy, pbc_lta_cpp_tidy)

bc_lta_combined <- rbind(kbc_lta_sbp_tidy, kbc_lta_dbp_tidy, 
                         kbc_lta_aix_tidy, kbc_lta_cpp_tidy,
                         pbc_lta_sbp_tidy, pbc_lta_dbp_tidy, 
                         pbc_lta_aix_tidy, pbc_lta_cpp_tidy)


all_pm_combined <- rbind(kpm_sbp_tidy, kpm_dbp_tidy, kpm_aix_tidy, kpm_cpp_tidy,
                     ppm_sbp_tidy, ppm_dbp_tidy, ppm_aix_tidy, ppm_cpp_tidy,
                     kpm_lta_sbp_tidy, kpm_lta_dbp_tidy, 
                     kpm_lta_aix_tidy, kpm_lta_cpp_tidy,
                     ppm_lta_sbp_tidy, ppm_lta_dbp_tidy, 
                     ppm_lta_aix_tidy, ppm_lta_cpp_tidy)

all_bc_combined <- rbind(kbc_sbp_tidy, kbc_dbp_tidy, kbc_aix_tidy, kbc_cpp_tidy,
                     pbc_sbp_tidy, pbc_dbp_tidy, pbc_aix_tidy, pbc_cpp_tidy,
                     kbc_lta_sbp_tidy, kbc_lta_dbp_tidy, 
                     kbc_lta_aix_tidy, kbc_lta_cpp_tidy,
                     pbc_lta_sbp_tidy, pbc_lta_dbp_tidy, 
                     pbc_lta_aix_tidy, pbc_lta_cpp_tidy)



# Plot results
pm_plot_estimates <- all_pm_combined %>%
  mutate(model = factor(model,
                        levels = c("Systolic BP", "Diastolic BP", 
                                   "Aug Index", "Cent Pulse Press"))) %>% 
  ggplot(aes()) +
  geom_point(aes(x=model, y=estimate, color = term, shape = term), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high, color = term), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5,
                    show.legend = FALSE) +
  theme_bw() +  
  geom_hline(yintercept = 0) +
  ggtitle(label = "") +
  labs(y = "Estimate: per ln increase in PM2.5") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 24, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 24, colour = "black"),
          axis.title.y = element_text(size = 24,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.title = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 24, colour = "black")) +
  scale_color_manual(values = colorblind_palette,
                     name = "Model") +
  scale_shape_manual(values = c(15, 16, 17, 18),
                     name = "Model")
pm_plot_estimates

# Save plot as jpg
ggsave("pm_plot_estimates.jpg", width = 12, height = 6.5)

bc_plot_estimates <- all_bc_combined %>%
  mutate(model = factor(model,
                        levels = c("Systolic BP", "Diastolic BP", 
                                   "Aug Index", "Cent Pulse Press"))) %>% 
  ggplot(aes()) +
  geom_point(aes(x=model, y=estimate, color = term, shape = term), 
             position = position_dodge(width = 0.5), size = 4) +
  geom_errorbar(aes(x=model, ymin=conf.low, ymax=conf.high, color = term), 
             position = position_dodge(width = 0.5), size = 1.2, width = 0.5,
                    show.legend = FALSE) +
  theme_bw() +  
  geom_hline(yintercept = 0) +
  ggtitle(label = "") +
  labs(y = "Estimate: per ln increase in BC") +
  labs(x = "", group = "", shape = "") +
  theme(title = element_text(size = 16), 
          axis.text.x = element_text(size = 24, colour = "black", angle = 45,
                                     hjust = 1, vjust = .8),
          axis.text.y = element_text(size = 24, colour = "black"),
          axis.title.y = element_text(size = 24,
                                      margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank(),
          legend.title = element_blank(),
          legend.position = "top",
          legend.text = element_text(size = 24, colour = "black")) +
  scale_color_manual(values = c("#88CCEE", "#CC6677", "#DDCC77", "#117733"),
                     name = "Model") +
  scale_shape_manual(values = c(15, 16, 17, 18),
                     name = "Model")
bc_plot_estimates

# Save plot as jpg
ggsave("bc_plot_estimates.jpg", width = 12, height = 6.5)
```
