---
title: "R00 Confounders Summary Stats"
author: "Ethan Walker"
date: "11 Jan 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 6)
```


```{r, message=FALSE}
library(tidyverse)
library(magrittr)
library(gridExtra)
library(lubridate)
library(haven)
library(knitr)
```

---

```{r}
#load full dataset
r00_full_joined_sphygmocor <- read_rds("output/r00_full_joined_sphygmocor.RDS")
```

# Secondary Stove Use
```{r}
sec_stove_stats <- r00_full_joined_sphygmocor %>% 
  select(aug_index, phase, days_sec, sec_stove, informed_consent) %>% 
  #na.exclude(days_sec) %>% 
  filter(phase == c(5,6)) 
table(sec_stove_stats$sec_stove)
```


# Summary Stats for entire study population with Sphygmocor data
### Data from phases 1 and 2
### Sphygmocor malfunction during phase 2
```{r}
### Why does total n not 230?
summary_stats <- r00_full_joined_sphygmocor %>% 
  select(house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total, aug_index) %>% 
  na.exclude(aug_index) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>% 
  filter(phase == 1 | phase == 2) %>% 
  select(-house_id, -age_baseline, -height, -weight, -bmi, -ses_materials,
         -beds_new, -dds_total, -aug_index) %>%
  group_by(phase) %>% 
  summarise_all(funs("_mean" = mean, "_sd" = sd, "_median" = median, 
                     "_min" = min, "_max" = max, "_n" = n())) %>% 
  gather(var, value, -phase) %>% 
  separate(var, into = c("var", "stat"), sep = "__") %>% 
  spread(stat, value) %>% 
  arrange(var, phase) %>% 
  select(var, phase, n, mean, sd, median, max, min) %>% 
  rename("Variable" = var, "Phase" = phase)
kable(summary_stats, digits = 2)
```

\pagebreak  

# Summary Stats grouped by study arm
### Data from phases 1 and 2
### Sphygmocor malfunction during phase 2
```{r}
summary_stats <- r00_full_joined_sphygmocor %>% 
  select(study_arm, house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total, aug_index) %>% 
  na.exclude(aug_index) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>% 
  filter(phase == 1 | phase == 2) %>% 
  select(-house_id, -age_baseline, -height, -weight, -bmi, -ses_materials,
         -beds_new, -dds_total, -aug_index) %>%
  group_by(study_arm, phase) %>% 
  summarise_all(funs("_mean" = mean, "_sd" = sd, "_median" = median, 
                     "_min" = min, "_max" = max, "_n" = n())) %>% 
  gather(var, value, -study_arm, -phase) %>% 
  separate(var, into = c("var", "stat"), sep = "__") %>% 
  spread(stat, value) %>% 
  arrange(var, phase, study_arm) %>% 
  select(var, phase, study_arm, n, mean, sd, median, max, min) %>% 
  rename("Variable" = var, "Phase" = phase, "Study Arm" = study_arm)
kable(summary_stats, digits = 2)
```

\pagebreak  

# Boxplots
### Phase 1 data
```{r}
## BMI
# boxplots by study arm
confounder_boxplot <- r00_full_joined_sphygmocor %>% 
  select(study_arm, house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total) %>% 
  filter(phase == 1) %>% 
  na.exclude(bmi) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>%
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot() +
  geom_boxplot(aes(study_arm, `Body Mass Index`)) +
  ggtitle("BMI by Study Arm") +
  xlab("Study Arm") +
  ylab("BMI (kg/m^2)") +
  theme_bw()
confounder_boxplot
```

\pagebreak  

```{r}
## Age
# boxplots by study arm
confounder_boxplot <- r00_full_joined_sphygmocor %>% 
  select(study_arm, house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total) %>% 
  filter(phase == 1) %>% 
  na.exclude(age_baseline) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>%
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot() +
  geom_boxplot(aes(study_arm, `Baseline Age`)) +
  ggtitle("Age by Study Arm") +
  xlab("Study Arm") +
  ylab("Age (years)") +
  theme_bw()
confounder_boxplot
```

\pagebreak  

```{r}
## SES
# boxplots by study arm
confounder_boxplot <- r00_full_joined_sphygmocor %>% 
  select(study_arm, house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total) %>% 
  filter(phase == 1) %>% 
  na.exclude(ses_materials) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>%
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot() +
  geom_boxplot(aes(study_arm, `SES Materials`)) +
  ggtitle("SES Materials by Study Arm") +
  xlab("Study Arm") +
  ylab("SES Materials (n)") +
  theme_bw()
confounder_boxplot
```

\pagebreak  

```{r}
## Beds
# boxplots by study arm
confounder_boxplot <- r00_full_joined_sphygmocor %>% 
  select(study_arm, house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total) %>% 
  filter(phase == 1) %>% 
  na.exclude(beds_new) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>%
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot() +
  geom_boxplot(aes(study_arm, `Beds Per Person`)) +
  ggtitle("Beds Per Person by Study Arm") +
  xlab("Study Arm") +
  ylab("Beds Per Person") +
  theme_bw()
confounder_boxplot
```

\pagebreak  

```{r}
## DDS
# boxplots by study arm
confounder_boxplot <- r00_full_joined_sphygmocor %>% 
  select(study_arm, house_id, phase, age_baseline, height, weight, bmi, ses_materials,
         beds_new, dds_total) %>% 
  filter(phase == 1) %>% 
  na.exclude(dds_total) %>% 
  mutate("Baseline Age" = as.numeric(age_baseline), 
         "Height" = as.numeric(height), 
         "Weight" = as.numeric(weight), 
         "Body Mass Index" = as.numeric(bmi), 
         "SES Materials" = as.numeric(ses_materials), 
         "Beds Per Person" = as.numeric(beds_new), 
         "Dietary Diversity Score" = as.numeric(dds_total)) %>%
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot() +
  geom_boxplot(aes(study_arm, `Dietary Diversity Score`)) +
  ggtitle("Dietary Diversity Score by Study Arm") +
  xlab("Study Arm") +
  ylab("Dietary Diversity Score") +
  theme_bw()
confounder_boxplot
```


