---
title: "Exposure Data Check"
author: "Ethan Walker"
date: "6 August 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
```

# This RMD is outdated
# Initial check of phase 6 pre and post filter weights after I finished weighing
# Megan BC has since processed all filter weights and exposure data

```{r, message=FALSE}
# Load data
#r00_p6_pre_weights <- read_csv("input/honduras_r00_p6_pre_weights.csv")
#r00_p6_post_weights <- read_csv("input/honduras_r00_p6_post_weights.csv")

r00_p6_weights_combined <- readRDS("output/r00_p6_weights_combined.rds")
r00_p6_pre_weights <- readRDS("output/r00_p6_pre_weights.rds")
r00_p6_post_weights <- readRDS("output/r00_p6_post_weights.rds")
```

##### Phase 6 initial exposure data check and cleaning #####
```{r}
# rename entry_check vars
r00_p6_pre_weights <- r00_p6_pre_weights %>% 
  rename(entry_check_pre = entry_check)
r00_p6_post_weights <- r00_p6_post_weights %>% 
  rename(entry_check_post = entry_check)

r00_p6_weights_combined <- full_join(r00_p6_pre_weights, r00_p6_post_weights, by = "filter_id")

# save datasets as RDS
saveRDS(r00_p6_weights_combined, "output/r00_p6_weights_combined.rds")
saveRDS(r00_p6_pre_weights, "output/r00_p6_pre_weights.rds")
saveRDS(r00_p6_post_weights, "output/r00_p6_post_weights.rds")
```

```{r}
# Initial data check on weights
weight_check <- r00_p6_weights_combined %>% 
  mutate(pre_post_diff = (average_post - average_pre)) %>% 
  mutate(pre_post_check = if_else(pre_post_diff < 0, "neg", "pos")) 

# P6-338 has no pre-weight -  post-weight entered correctly - P6-238 entered twice
 #### Changed in database ####
# P6-217 has no pre-weight -  post-weight entered correctly - P6-218 entered twice
 #### Changed in database ####
# P6-162 has no pre-weight -  post-weight entered correctly - P6-126 entered twice
 #### Changed in database ####
# P6-498 entered twice 
 #### The one with pre-weight of 109.801 (higher than post-weight) was renamed to P6-468 (missing from pre-weights) ####

# P6-247 entered correctly - reweigh
# P6-339 entered correctly - reweigh
# P6-405 entered correctly - reweigh
# P6-078 entered correctly - reweigh - "dropped prior to weighing (pre)"
# P6-442 entered correctly - reweigh
# P6-074 entered correctly - reweigh - pre trip colocation
# P6-475 entered correctly - reweigh
# P6-395 entered correctly - less than 0.01 difference, don't reweigh
# P6-328 entered correctly - less than 0.01 difference, don't reweigh
# P6-424 entered correctly - less than 0.01 difference, don't reweigh
# P6-176 entered correctly - less than 0.01 difference, don't reweigh
# P6-427 entered correctly - less than 0.01 difference, don't reweigh
# P6-280 entered correctly - less than 0.01 difference, don't reweigh
# P6-121 entered correctly - same pre/post weight, don't reweigh
# P6-031 entered correctly - same pre/post weight, don't reweigh
```
