---
title: "Honduras R00 Inital Models"
author: "Ethan Walker"
date: "14 Nov 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 10)
```


```{r, include=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(purrr)
library(car)
library(forcats)
library(readxl)
library(naniar)
library(splines)
```

# Inital look at mixed model analysis
# This file now outdated

```{r}
#r00_sample_wide <- read_xlsx("input/data_meeting_14nov2018.xlsx")

r00_sample_repeated_by_phase <- read_rds("output/r00_sample_repeated_by_phase.RDS")
```

##### Convert Sample Dataset from Wide to Long #####
```{r}
r00_sample_long <- r00_sample_wide %>% 
  #creating new variables for phases 2-6 if it was only collected at phase 1
  mutate(study_arm_r00_p1 = Study_Arm_r00_p2, 
         study_arm_r00_p2 = Study_Arm_r00_p2,
         study_arm_r00_p3 = Study_Arm_r00_p2, 
         study_arm_r00_p4 = Study_Arm_r00_p2, 
         study_arm_r00_p5 = Study_Arm_r00_p2, 
         study_arm_r00_p6 = Study_Arm_r00_p2) %>% 
  mutate(age_baseline_r00_p2 = age_baseline_r00_p1, 
         age_baseline_r00_p3 = age_baseline_r00_p1,
         age_baseline_r00_p4 = age_baseline_r00_p1, 
         age_baseline_r00_p5 = age_baseline_r00_p1, 
         age_baseline_r00_p6 = age_baseline_r00_p1) %>% 
  select(-Study_Arm_r00_p2) %>% 
  #transform data to long format with only 3 columns
  gather(key = "variable", value = "value", -house_id) %>% 
  #arrange data by house_id, descending
  arrange(house_id)

r00_sample_repeated_by_phase <- r00_sample_long %>%
  #this variable has no corresponding phase
  #renaming to phase 1 so it spreads below
  #mutate(variable = if_else(variable == "group", 
   #                         "group_r00_p1", variable)) %>%
  #separate variable to create new phase column
  separate(variable, c("variable", "phase"), sep = "_r00_p") %>%
  mutate(value = if_else(value == ".", "99999", value)) %>% 
  replace_with_na(replace = list(value = 99999)) %>% 
  #separate phase and "new", then attach "new" to variable
  separate(phase, c("phase", "new"), sep = "_") %>% 
  unite("variable", c("variable", "new")) %>% 
  #remove NA from end of variables that was added above
  separate(variable, c("variable", "trash"), sep = "_NA") %>% 
  select(-"trash") %>% 
  #spread out into columns, grouped by house_id and phase
  spread(key = "variable", value = "value") %>% 
  arrange(house_id) %>% 
  mutate(sysbp = as.numeric(sysbp))%>% 
  mutate(diabp = as.numeric(diabp)) %>% 
  mutate(age = if_else(age_baseline > 40, 1, 0))

write_rds(r00_sample_repeated_by_phase, "output/r00_sample_repeated_by_phase.RDS")
```

## Honduras R00 Initial Model ##
```{r}
#use date of visit in place of phase and try df=12
bp_model_spline <- lmer(sysbp ~ assigned_stove + ns(phase, df=2) + 
                          (1 | house_id), r00_sample_repeated_by_phase)

bp_model_phase <- lmer(sysbp ~ assigned_stove + factor(phase) + 
                         (1 | house_id), r00_sample_repeated_by_phase)

bp_model <- lmer(sysbp ~ assigned_stove + (1 | house_id), r00_sample_repeated_by_phase)

summary(bp_model_spline)

summary(bp_model_phase)

summary(bp_model)


# save model results
write_rds(bp_model, "output/bp_model_test_11nov18.RDS")
```

## Format model output for plotting
```{r}
tidy_results_bp_model_phase <- tidy(bp_model_phase, conf.int = TRUE) %>% 
    filter(grepl('assigned', term)) %>% 
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(term = if_else(term == "assigned_stove1", "justa", "na"))
```

## Plot model estimate
```{r}
plot_sample_estimates <- tidy_results_bp_model_phase %>%
  ggplot() +
  geom_point(aes(x=1, y=estimate)) +
  geom_errorbar(aes(x=1, ymin=ci_low, ymax=ci_hi)) +
  theme_minimal() +
  geom_hline(yintercept = 0) +
  ggtitle(label = "R00 Augmentation Index Model") +
  labs(x = "")
plot_sample_estimates
```
