---
title: "R00 Secondary Models"
author: "Ethan Walker"
date: "9 Jan 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 10)
```


```{r, include=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(purrr)
library(car)
library(forcats)
library(readxl)
library(naniar)
library(splines)
library(lubridate)
jvPalette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
#load full dataset
r00_full_joined_sphygmocor <- read_rds("output/r00_full_joined_sphygmocor.RDS")
r00_full_long <- read_rds("output/r00_full_repeated_by_phase.rds")

# USE THIS DATASET FOR ANALYSES!!!
## Removes values >75 for AIx and CPP, and <-25 for AIx
r00_model_data_outliers_removed <- read_rds("output/r00_model_data_outliers_removed.RDS")
```


```{r}
r00_model_data <- r00_model_data_outliers_removed %>% 
  filter(!is.na(study_arm)) %>% 
  filter(pregnant_new == 0) 

# Dataset for participants who have AIx data for all 6 Phases (107 participants)
r00_data_6phases <- r00_model_data_outliers_removed %>%
  group_by(house_id) %>% 
  #create new var to be able to filter for participants that completed 6 phases
  mutate(phase_complete = if_else(!is.na(aug_index), 1, 0)) %>% 
  filter(sum(phase_complete) == 6) %>% 
  mutate(all_phases = "yes") %>% 
  ungroup() 

# Dataset for participants who have AIx data for all <6 Phases
r00_data_5phases <- r00_model_data_outliers_removed %>%
  group_by(house_id) %>% 
  #create new var to be able to filter for participants that completed 6 phases
  mutate(phase_complete = if_else(!is.na(aug_index), 1, 0)) %>% 
  filter(sum(phase_complete) < 6) %>% 
  mutate(all_phases = "no") %>% 
  ungroup() 

# combine 6 phases and <6 phases datasets with indicator variable to group by
r00_56_combined <- rbind(r00_data_6phases, r00_data_5phases)
```


```{r}
## Prep data for T-Tests
# Filter for within arm t-tests - AIx
aix_arm1_phase13 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 3)) %>% 
  select(aug_index, assigned_stove, house_id) %>% 
  spread(assigned_stove, aug_index) %>% 
  na.omit()

aix_arm1_phase14 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 4)) %>% 
  select(aug_index, assigned_stove, house_id) %>% 
  spread(assigned_stove, aug_index) %>% 
  na.omit()

aix_arm1_phase15 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 5)) %>% 
  select(aug_index, assigned_stove, house_id) %>% 
  spread(assigned_stove, aug_index) %>% 
  na.omit()

aix_arm1_phase16 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 6)) %>% 
  select(aug_index, assigned_stove, house_id) %>% 
  spread(assigned_stove, aug_index) %>% 
  na.omit()

aix_arm2_phase15 <- r00_model_data %>% 
  filter(study_arm == 2 & (phase == 1 | phase == 5)) %>% 
  select(aug_index, assigned_stove, house_id) %>% 
  spread(assigned_stove, aug_index) %>% 
  na.omit()

aix_arm2_phase16 <- r00_model_data %>% 
  filter(study_arm == 2 & (phase == 1 | phase == 6)) %>% 
  select(aug_index, assigned_stove, house_id) %>% 
  spread(assigned_stove, aug_index) %>% 
  na.omit()


# Filter for within arm t-tests - CPP
cpp_arm1_phase13 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 3)) %>% 
  select(pulse_pressure_central, assigned_stove, house_id) %>% 
  spread(assigned_stove, pulse_pressure_central) %>% 
  na.omit()

cpp_arm1_phase14 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 4)) %>% 
  select(pulse_pressure_central, assigned_stove, house_id) %>% 
  spread(assigned_stove, pulse_pressure_central) %>% 
  na.omit()

cpp_arm1_phase15 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 5)) %>% 
  select(pulse_pressure_central, assigned_stove, house_id) %>%
  spread(assigned_stove, pulse_pressure_central) %>% 
  na.omit()

cpp_arm1_phase16 <- r00_model_data %>% 
  filter(study_arm == 1 & (phase == 1 | phase == 6)) %>% 
  select(pulse_pressure_central, assigned_stove, house_id) %>% 
  spread(assigned_stove, pulse_pressure_central) %>% 
  na.omit()

cpp_arm2_phase15 <- r00_model_data %>% 
  filter(study_arm == 2 & (phase == 1 | phase == 5)) %>% 
  select(pulse_pressure_central, assigned_stove, house_id) %>% 
  spread(assigned_stove, pulse_pressure_central) %>% 
  na.omit()

cpp_arm2_phase16 <- r00_model_data %>% 
  filter(study_arm == 2 & (phase == 1 | phase == 6)) %>% 
  select(pulse_pressure_central, assigned_stove, house_id) %>% 
  spread(assigned_stove, pulse_pressure_central) %>% 
  na.omit()



# Filter for across arm t-tests
r00_arm1_phase3 <- r00_model_data %>% 
  filter(study_arm == 1 & phase == 3) %>% 
  filter(!is.na(aug_index))

r00_arm1_phase4 <- r00_model_data %>% 
  filter(study_arm == 1 & phase == 4) %>% 
  filter(!is.na(aug_index))

r00_arm2_phase3 <- r00_model_data %>% 
  filter(study_arm == 2 & phase == 3) %>% 
  filter(!is.na(aug_index))

r00_arm2_phase4 <- r00_model_data %>% 
  filter(study_arm == 2 & phase == 4) %>% 
  filter(!is.na(aug_index))
```

# AIx T-Tests
```{r}
## R00 T-Tests
## Comparisons within Arm 1
arm1_phase1vs3_ttest <- t.test(aix_arm1_phase13$Traditional, aix_arm1_phase13$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs3_ttest

arm1_phase1vs4_ttest <- t.test(aix_arm1_phase14$Traditional, aix_arm1_phase14$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs4_ttest

arm1_phase1vs5_ttest <- t.test(aix_arm1_phase15$Traditional, aix_arm1_phase15$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs5_ttest

arm1_phase1vs6_ttest <- t.test(aix_arm1_phase16$Traditional, aix_arm1_phase16$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs6_ttest




## Comparisons within Arm 2
arm2_phase1vs5_ttest <- t.test(aix_arm2_phase15$Traditional, aix_arm2_phase15$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm2_phase1vs5_ttest

arm2_phase1vs6_ttest <- t.test(aix_arm2_phase16$Traditional, aix_arm2_phase16$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm2_phase1vs6_ttest



## Comparisons between Arms at Phases 3 and 4
arm1vs2_phase3_ttest <- t.test(r00_arm1_phase3$aug_index, r00_arm2_phase3$aug_index, 
                               mu = 0, paired = FALSE, var.equal = FALSE)
arm1vs2_phase3_ttest

arm1vs2_phase4_ttest <- t.test(r00_arm1_phase4$aug_index, r00_arm2_phase4$aug_index, 
                               mu = 0, paired = FALSE, var.equal = FALSE)
arm1vs2_phase4_ttest
```


```{r}
## Format estimates
tidy_arm1_phase1vs3_ttest <- tidy(arm1_phase1vs3_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs3")
tidy_arm1_phase1vs4_ttest <- tidy(arm1_phase1vs4_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs4")
tidy_arm1_phase1vs5_ttest <- tidy(arm1_phase1vs5_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs5")
tidy_arm1_phase1vs6_ttest <- tidy(arm1_phase1vs6_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs6")

arm1_within_group <- rbind(tidy_arm1_phase1vs3_ttest,
                           tidy_arm1_phase1vs4_ttest,
                           tidy_arm1_phase1vs5_ttest,
                           tidy_arm1_phase1vs6_ttest)


tidy_arm2_phase1vs5_ttest <- tidy(arm2_phase1vs5_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs5")
tidy_arm2_phase1vs6_ttest <- tidy(arm2_phase1vs6_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs6")

arm2_within_group <- rbind(tidy_arm2_phase1vs5_ttest,
                           tidy_arm2_phase1vs6_ttest)


tidy_arm1vs2_phase3_ttest <- tidy(arm1vs2_phase3_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 3")
tidy_arm1vs2_phase4_ttest <- tidy(arm1vs2_phase4_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 4")

between_groups <- rbind(tidy_arm1vs2_phase3_ttest,
                        tidy_arm1vs2_phase4_ttest)
```


```{r, fig.width=10, fig.height=7.5}
## Plot model estimate
arm_1_plot <- arm1_within_group %>%
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  geom_errorbar(aes(x=model, ymin=ci_low, ymax=ci_hi), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  
  ##### Update outcome in title below #####

  ggtitle(label = "AIx Models: Arm 1 Within Group T-Tests") +
  labs(y = "Estimate: Difference Between Phases") +
  labs(x = "") +
  theme(title = element_text(size = 19), 
          axis.text.x = element_text(angle = 15, hjust = 1, 
                                     size = 18, colour = "black"),
          axis.text.y = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank()) +
  scale_colour_manual(values=jvPalette) 
arm_1_plot

arm_2_plot <- arm2_within_group %>%
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  geom_errorbar(aes(x=model, ymin=ci_low, ymax=ci_hi), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  
  ##### Update outcome in title below #####

  ggtitle(label = "AIx Models: Arm 2 Within Group T-Tests") +
  labs(y = "Estimate: Difference Between Phases") +
  labs(x = "") +
  theme(title = element_text(size = 19), 
          axis.text.x = element_text(angle = 15, hjust = 1, 
                                     size = 18, colour = "black"),
          axis.text.y = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank()) +
  scale_colour_manual(values=jvPalette) 
arm_2_plot

between_group_plot <- between_groups %>%
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  geom_errorbar(aes(x=model, ymin=ci_low, ymax=ci_hi), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  
  ##### Update outcome in title below #####

  ggtitle(label = "AIx Models: Between Group T-Tests") +
  labs(y = "Estimate: Arm 1 compared to Arm 2") +
  labs(x = "") +
  theme(title = element_text(size = 19), 
          axis.text.x = element_text(angle = 15, hjust = 1, 
                                     size = 18, colour = "black"),
          axis.text.y = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank()) +
  scale_colour_manual(values=jvPalette) 
between_group_plot
```

# CPP T-Tests
```{r}
## R00 T-Tests
## Comparisons within Arm 1
arm1_phase1vs3_ttest <- t.test(cpp_arm1_phase13$Traditional, cpp_arm1_phase13$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs3_ttest

arm1_phase1vs4_ttest <- t.test(cpp_arm1_phase14$Traditional, cpp_arm1_phase14$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs4_ttest

arm1_phase1vs5_ttest <- t.test(cpp_arm1_phase15$Traditional, cpp_arm1_phase15$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs5_ttest

arm1_phase1vs6_ttest <- t.test(cpp_arm1_phase16$Traditional, cpp_arm1_phase16$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm1_phase1vs6_ttest




## Comparisons within Arm 2
arm2_phase1vs5_ttest <- t.test(cpp_arm2_phase15$Traditional, cpp_arm2_phase15$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm2_phase1vs5_ttest

arm2_phase1vs6_ttest <- t.test(cpp_arm2_phase16$Traditional, cpp_arm2_phase16$Justa, 
                               mu = 0, paired = TRUE, var.equal = TRUE)
arm2_phase1vs6_ttest



## Comparisons between Arms at Phases 3 and 4
arm1vs2_phase3_ttest <- t.test(r00_arm1_phase3$pulse_pressure_central, 
                               r00_arm2_phase3$pulse_pressure_central, 
                               mu = 0, paired = FALSE, var.equal = FALSE)
arm1vs2_phase3_ttest

arm1vs2_phase4_ttest <- t.test(r00_arm1_phase4$pulse_pressure_central, 
                               r00_arm2_phase4$pulse_pressure_central, 
                               mu = 0, paired = FALSE, var.equal = FALSE)
arm1vs2_phase4_ttest
```


```{r}
## Format estimates
tidy_arm1_phase1vs3_ttest <- tidy(arm1_phase1vs3_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs3")
tidy_arm1_phase1vs4_ttest <- tidy(arm1_phase1vs4_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs4")
tidy_arm1_phase1vs5_ttest <- tidy(arm1_phase1vs5_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs5")
tidy_arm1_phase1vs6_ttest <- tidy(arm1_phase1vs6_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs6")

arm1_within_group <- rbind(tidy_arm1_phase1vs3_ttest,
                           tidy_arm1_phase1vs4_ttest,
                           tidy_arm1_phase1vs5_ttest,
                           tidy_arm1_phase1vs6_ttest)


tidy_arm2_phase1vs5_ttest <- tidy(arm2_phase1vs5_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs5")
tidy_arm2_phase1vs6_ttest <- tidy(arm2_phase1vs6_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 1vs6")

arm2_within_group <- rbind(tidy_arm2_phase1vs5_ttest,
                           tidy_arm2_phase1vs6_ttest)


tidy_arm1vs2_phase3_ttest <- tidy(arm1vs2_phase3_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 3")
tidy_arm1vs2_phase4_ttest <- tidy(arm1vs2_phase4_ttest, conf.int = TRUE) %>%
    rename(ci_low = conf.low, ci_hi = conf.high) %>% 
    mutate(model = "Phase 4")

between_groups <- rbind(tidy_arm1vs2_phase3_ttest,
                        tidy_arm1vs2_phase4_ttest)
```


```{r, fig.width=10, fig.height=7.5}
## Plot model estimate
arm_1_plot <- arm1_within_group %>%
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  geom_errorbar(aes(x=model, ymin=ci_low, ymax=ci_hi), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  
  ##### Update outcome in title below #####

  ggtitle(label = "Central Pulse Pressure Models: Arm 1 Within Group T-Tests") +
  labs(y = "Estimate: Difference Between Phases") +
  labs(x = "") +
  theme(title = element_text(size = 19), 
          axis.text.x = element_text(angle = 15, hjust = 1, 
                                     size = 18, colour = "black"),
          axis.text.y = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank()) +
  scale_colour_manual(values=jvPalette) 
arm_1_plot

arm_2_plot <- arm2_within_group %>%
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  geom_errorbar(aes(x=model, ymin=ci_low, ymax=ci_hi), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  
  ##### Update outcome in title below #####

  ggtitle(label = "Central Pulse Pressure Models: Arm 2 Within Group T-Tests") +
  labs(y = "Estimate: Difference Between Phases") +
  labs(x = "") +
  theme(title = element_text(size = 19), 
          axis.text.x = element_text(angle = 15, hjust = 1, 
                                     size = 18, colour = "black"),
          axis.text.y = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank()) +
  scale_colour_manual(values=jvPalette) 
arm_2_plot

between_group_plot <- between_groups %>%
  ggplot() +
  geom_point(aes(x=model, y=estimate), size = 4) +
  geom_errorbar(aes(x=model, ymin=ci_low, ymax=ci_hi), 
                size = 1.2, width = 0.5) +
  geom_hline(yintercept = 0) +
  theme_bw() +
  
  ##### Update outcome in title below #####

  ggtitle(label = "Central Pulse Pressure Models: Between Group T-Tests") +
  labs(y = "Estimate: Arm 1 compared to Arm 2") +
  labs(x = "") +
  theme(title = element_text(size = 19), 
          axis.text.x = element_text(angle = 15, hjust = 1, 
                                     size = 18, colour = "black"),
          axis.text.y = element_text(size = 18, colour = "black"),
          axis.title.y = element_text(size = 18),
          axis.line.x = element_line(colour = "black", size = 1.2), 
          axis.line.y = element_line(colour = "black", size = 1.2), 
          axis.ticks = element_blank(), 
          panel.border = element_blank(), 
          panel.grid = element_blank()) +
  scale_colour_manual(values=jvPalette) 
between_group_plot
```