---
title: "R00 Stove Use Models"
author: "Ethan Walker"
date: "June 26, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      fig.width = 8, fig.height = 5)
```


```{r, include=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(purrr)
library(car)
library(forcats)
library(readxl)
library(naniar)
library(splines)
library(lubridate)
library(knitr)
library(influence.ME)
library(boxcoxmix)
library(gamm4)
library(sjstats)
jvPalette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

```{r}
# load full dataset
# r00_full_long <- read_rds("output/r00_full_repeated_by_phase.rds")

# USE THIS DATASET FOR ANALYSES!!!
## Removes values >75 for AIx and CPP, and <-25 for AIx (10 total)
r00_model_data_outliers_removed <- read_rds("output/r00_model_data_outliers_removed.RDS")

stove_use_data <- r00_model_data_outliers_removed %>% 
  filter(!is.na(assigned_stove))

# Filtering out medication users
r00_model_data_meds <- stove_use_data %>% 
  #filtering out bp med users
  filter(is.na(med_bp))

# Dataset for participants who have AIx data for all 6 Phases
r00_model_data_6phases <- stove_use_data %>% 
  group_by(house_id) %>% 
  #create new var to be able to filter for participants that completed 6 phases
  mutate(phase_complete = if_else(!is.na(aug_index), 1, 0)) %>% 
  filter(sum(phase_complete) == 6)
```

# Analysis plan
```{r}
test_data <- r00_model_data_outliers_removed %>% 
  filter(!is.na(assigned_stove)) %>% 
  # mutating so NAs are reported as 0
  # days_sec is self-reported use of secondary stove in days/month
  mutate(days_sec = as.numeric(days_sec),
         days_sec = if_else(days_sec == 0 | is.na(days_sec), 0, days_sec)) %>% 
  # days_sec is self-reported use of secondary stove in days/month
  mutate(hours_primary = as.numeric(hours_primary),
         hours_primary = if_else(hours_primary == 0 | is.na(hours_primary), 
                                 0, hours_primary))

median(test_data$days_sec) # 1 day
hist(test_data$days_sec, breaks = 30)
median(test_data$hours_primary) # 3 hours
hist(test_data$hours_primary)
# Could dichotomize days_sec at 0 days or 1+ days
table(test_data$days_sec)
# However, the group of interest (justa+trad) only reported 0 days/month 14 times
# Consider dichotomizing days_sec at < 4 or 4+ days per month
table(test_data$days_sec, test_data$stove_use_3)
# Could dichotomize hours_primary at median of 3 (<3.5, 3.5+)
table(test_data$hours_primary)
table(test_data$hours_primary, test_data$stove_use_3)

# dataset with new variables for analysis
stove_use_data <- test_data %>% 
  # splitting days_sec at <4 and 4+
  mutate(days_sec_4 = if_else(days_sec < 4, 0, 1)) %>%
  mutate(days_sec_4 = factor(days_sec_4, levels = c(0,1), labels = c("<4", "4+"))) %>%
  # splitting hours_primary at <3.5 and 3.5+
  mutate(hours_primary_3.5 = if_else(hours_primary < 3.5, 0, 1)) %>%
  mutate(hours_primary_3.5 = factor(hours_primary_3.5, 
                                    levels = c(0,1), labels = c("<3.5", "3.5+"))) %>%
  # mutating stove_use_3 to character for use in if_else statement
  mutate(stove_use_3 = as.character(stove_use_3)) %>% 
  # new variable incorporating days/month of secondary stove use (<4 vs 4+) 
  # only doing this for justa+trad levels
  ## because only 24 people reported 4+ days improved secondary stove use with Justa
  ## and this data wasn't available in phase 1
  mutate(stove_use_days_stack = 
         if_else(stove_use_3 == "justa+trad" & days_sec_4 == "4+",
                 "justa+trad, 4+", stove_use_3)) %>% 
  mutate(stove_use_days_stack = 
           factor(stove_use_days_stack,
                  levels = c("justa/imprvd", "justa+trad", 
                             "justa+trad, 4+", "trad"),
                  labels = c("justa/imprvd", "justa+trad, <4", 
                             "justa+trad, 4+", "trad"))) %>%
  # reorder new var so traditional is reference
  mutate(stove_use_days_stack = 
           factor(stove_use_days_stack,
                  levels = c("trad", "justa+trad, 4+", 
                             "justa+trad, <4", "justa/imprvd"))) %>%
  # new variable incorporating hours/day of primary stove use (<3.5 vs 3.5+) 
  mutate(stove_use_hours = 
         if_else(stove_use_3 == "justa+trad" & hours_primary_3.5 == "3.5+",
                 "justa+trad, 3.5+", stove_use_3)) %>% 
  mutate(stove_use_hours = 
         if_else(stove_use_hours == "trad" & hours_primary_3.5 == "3.5+",
                 "trad, 3.5+", stove_use_hours)) %>% 
  mutate(stove_use_hours = 
         if_else(stove_use_hours == "justa/imprvd" & hours_primary_3.5 == "3.5+",
                 "justa/imprvd, 3.5+", stove_use_hours)) %>% 
  mutate(stove_use_hours = 
           factor(stove_use_hours,
                  levels = c("justa/imprvd", "justa/imprvd, 3.5+", "justa+trad", 
                             "justa+trad, 3.5+", "trad", "trad, 3.5+"),
                  labels = c("justa/imprvd, <3.5", "justa/imprvd, 3.5+", "justa+trad, <3.5", 
                             "justa+trad, 3.5+", "trad, <3.5", "trad, 3.5+"))) %>%
  # reorder new var so traditional 3.5+ hours is reference
  mutate(stove_use_hours = 
           factor(stove_use_hours,
                  levels = c("trad, 3.5+", "trad, <3.5", "justa+trad, 3.5+", 
                             "justa+trad, <3.5", "justa/imprvd, 3.5+", 
                             "justa/imprvd, <3.5"))) %>%
  mutate(stove_use_3 = factor(stove_use_3, 
                            levels = c("trad", "justa+trad", "justa/imprvd")))

table(stove_use_data$days_sec_4, stove_use_data$stove_use_3)
table(stove_use_data$days_sec_4, stove_use_data$stove_use_days_stack)
table(stove_use_data$hours_primary_3.5, stove_use_data$stove_use_3)
table(stove_use_data$hours_primary_3.5, stove_use_data$stove_use_hours)
```


# Stove use analyses with a priori confounders
## Try following variables as main IV in primary model:
### stove_use_3, stove_use_days_stack, stove_use_hours
```{r}
# AIx and Stove use variables

##### AIx and stove_use_3

model_stove_use_3 <- lmer(aug_index ~ stove_use_3 + 
                        ns(date_sphygmo, df=6) + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_stove_use_3)
tidy_model_stove_use_3 <- tidy(model_stove_use_3, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "stove_use_3") 


##### AIx and stove_use_3 - bp meds removed (57 obs)
model_no_bp_meds <- lmer(aug_index ~ stove_use_3 + 
                             ns(date_sphygmo, df=6) + age_baseline +
                             waist_cm + school_bi + (1 | house_id), 
                             r00_model_data_meds)
#summary(model_no_bp_meds)
tidy_model_no_bp_meds <- tidy(model_no_bp_meds, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "bp meds removed")

##### AIx and stove_use_3 - dichotomous confounders
model_di_conf <- lmer(aug_index ~ stove_use_3 + 
                          ns(date_sphygmo, df=6) + age_cat_40 +
                          waist_cat + school_bi + (1 | house_id), 
                          stove_use_data)
#summary(model_di_conf)
tidy_model_di_conf <- tidy(model_di_conf, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "dichotomous confounders")

##### AIx and stove_use_3 - date spline with 12 df
model_spline12 <- lmer(aug_index ~ stove_use_3 + 
                           ns(date_sphygmo, df=12) + age_baseline +
                           waist_cm + school_bi + (1 | house_id), 
                           stove_use_data)
#summary(model_spline12)
tidy_model_spline12 <- tidy(model_spline12, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "spline with 12 df")

##### AIx and stove_use_3 6 phases model 
model_6phases <- lmer(aug_index ~ stove_use_3 + 
                          ns(date_sphygmo, df=6) + age_baseline +
                          waist_cm + school_bi + (1 | house_id), 
                          r00_model_data_6phases)
#summary(model_6phases)
tidy_model_6phases <- tidy(model_6phases, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "6 phases")

##### AIx and stove_use_3 reduced model 
model_reduced <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) +
                         (1 | house_id), stove_use_data)
#summary(model_reduced)
tidy_model_reduced <- tidy(model_reduced, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "reduced")

##### AIx and stove_use_3 - phase instead of spline
model_phase <- lmer(aug_index ~ stove_use_3 + phase + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_phase)
tidy_model_phase <- tidy(model_phase, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "phase")

##### AIx and stove_use_3 - season instead of spline
model_season <- lmer(aug_index ~ stove_use_3 + season + age_baseline +
                         waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_season)
tidy_model_season <- tidy(model_season, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "season")

##### AIx and stove_use_3 - bmi instead of waist_cm
model_bmi <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      bmi + school_bi + (1 | house_id), stove_use_data)
#summary(model_bmi)
tidy_model_bmi <- tidy(model_bmi, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "bmi")

##### AIx and stove_use_3 - whr instead of waist_cm
model_whr <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      whr + school_bi + (1 | house_id), stove_use_data)
#summary(model_whr)
tidy_model_whr <- tidy(model_whr, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "whr")

##### AIx and stove_use_3 - adding beds_new
model_beds <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + beds_new + (1 | house_id), stove_use_data)
#summary(model_beds)
tidy_model_beds <- tidy(model_beds, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "beds_new")

##### AIx and stove_use_3 - adding ses_materials
model_ses <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + ses_materials + (1 | house_id), stove_use_data)
#summary(model_ses)
tidy_model_ses <- tidy(model_ses, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "ses_materials")

##### AIx and stove_use_3 - adding phys_act
model_pa <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                     waist_cm + school_bi + phys_act + (1 | house_id), stove_use_data)
#summary(model_pa)
tidy_model_pa <- tidy(model_pa, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "phys_act")

##### AIx and stove_use_3 - adding dds_total
model_dds <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + dds_total + (1 | house_id), stove_use_data)
#summary(model_dds)
tidy_model_dds <- tidy(model_dds, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "dds_total")

##### AIx and stove_use_3 - full model with all potential confounders
model_full <- lmer(aug_index ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + dds_total + phys_act +
                       ses_materials + beds_new + 
                       (1 | house_id), stove_use_data)
#summary(model_full)
tidy_model_full <- tidy(model_full, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "full")



##### AIx and stove_use_days_stack

model_stove_use_days <- lmer(aug_index ~ stove_use_days_stack + 
                        ns(date_sphygmo, df=6) + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_stove_use_days)
tidy_model_stove_use_days <- tidy(model_stove_use_days, conf.int = TRUE) %>% 
    filter(grepl('stove_use', term)) %>% 
    mutate(model = "stove use days") 


##### AIx and stove_use_hours

model_stove_use_hours <- lmer(aug_index ~ stove_use_hours + 
                        ns(date_sphygmo, df=6) + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_stove_use_hours)
tidy_model_stove_use_hours <- tidy(model_stove_use_hours, conf.int = TRUE) %>% 
    filter(grepl('stove_use', term)) %>% 
    mutate(model = "stove use hours") 

aix_results <- rbind(tidy_model_stove_use_3,
                     tidy_model_no_bp_meds,
                     tidy_model_6phases,
                     tidy_model_phase,
                     tidy_model_season,
                     tidy_model_spline12,
                     tidy_model_bmi,
                     tidy_model_whr,
                     tidy_model_beds,
                     tidy_model_ses,
                     tidy_model_pa,
                     tidy_model_dds,
                     tidy_model_full,
                     tidy_model_reduced,
                     tidy_model_stove_use_days,
                     tidy_model_stove_use_hours)
#kable(aix_results)
```


# Stove use analyses with a priori confounders
## Try following variables as main IV in primary model:
### stove_use_3, stove_use_days_stack, stove_use_hours
```{r}
# CPP and Stove use variables

##### CPP and stove_use_3

model_stove_use_3 <- lmer(pulse_pressure_central ~ stove_use_3 + 
                        ns(date_sphygmo, df=6) + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_stove_use_3)
tidy_model_stove_use_3 <- tidy(model_stove_use_3, conf.int = TRUE) %>% 
    filter(grepl('stove_use', term)) %>% 
    mutate(model = "stove use") 


##### CPP and stove_use_3 - bp meds removed (57 obs)
model_no_bp_meds <- lmer(pulse_pressure_central ~ stove_use_3 + 
                             ns(date_sphygmo, df=6) + age_baseline +
                             waist_cm + school_bi + (1 | house_id), 
                             r00_model_data_meds)
#summary(model_no_bp_meds)
tidy_model_no_bp_meds <- tidy(model_no_bp_meds, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "bp meds removed")

##### CPP and stove_use_3 - dichotomous confounders
model_di_conf <- lmer(pulse_pressure_central ~ stove_use_3 + 
                          ns(date_sphygmo, df=6) + age_cat_40 +
                          waist_cat + school_bi + (1 | house_id), 
                          stove_use_data)
#summary(model_di_conf)
tidy_model_di_conf <- tidy(model_di_conf, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "dichotomous confounders")

##### CPP and stove_use_3 - date spline with 12 df
model_spline12 <- lmer(pulse_pressure_central ~ stove_use_3 + 
                           ns(date_sphygmo, df=12) + age_baseline +
                           waist_cm + school_bi + (1 | house_id), 
                           stove_use_data)
#summary(model_spline12)
tidy_model_spline12 <- tidy(model_spline12, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "spline with 12 df")

##### CPP and stove_use_3 6 phases model 
model_6phases <- lmer(pulse_pressure_central ~ stove_use_3 + 
                          ns(date_sphygmo, df=6) + age_baseline +
                          waist_cm + school_bi + (1 | house_id), 
                          r00_model_data_6phases)
#summary(model_6phases)
tidy_model_6phases <- tidy(model_6phases, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "6 phases")

##### CPP and stove_use_3 reduced model 
model_reduced <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) +
                         (1 | house_id), stove_use_data)
#summary(model_reduced)
tidy_model_reduced <- tidy(model_reduced, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "reduced")

##### CPP and stove_use_3 - phase instead of spline
model_phase <- lmer(pulse_pressure_central ~ stove_use_3 + phase + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_phase)
tidy_model_phase <- tidy(model_phase, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "phase")

##### CPP and stove_use_3 - season instead of spline
model_season <- lmer(pulse_pressure_central ~ stove_use_3 + season + age_baseline +
                         waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_season)
tidy_model_season <- tidy(model_season, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "season")

##### CPP and stove_use_3 - bmi instead of waist_cm
model_bmi <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      bmi + school_bi + (1 | house_id), stove_use_data)
#summary(model_bmi)
tidy_model_bmi <- tidy(model_bmi, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "bmi")

##### CPP and stove_use_3 - whr instead of waist_cm
model_whr <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      whr + school_bi + (1 | house_id), stove_use_data)
#summary(model_whr)
tidy_model_whr <- tidy(model_whr, conf.int = TRUE) %>% 
    filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "whr")

##### CPP and stove_use_3 - adding beds_new
model_beds <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + beds_new + (1 | house_id), stove_use_data)
#summary(model_beds)
tidy_model_beds <- tidy(model_beds, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "beds_new")

##### CPP and stove_use_3 - adding ses_materials
model_ses <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + ses_materials + (1 | house_id), stove_use_data)
#summary(model_ses)
tidy_model_ses <- tidy(model_ses, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "ses_materials")

##### CPP and stove_use_3 - adding phys_act
model_pa <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                     waist_cm + school_bi + phys_act + (1 | house_id), stove_use_data)
#summary(model_pa)
tidy_model_pa <- tidy(model_pa, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "phys_act")

##### CPP and stove_use_3 - adding dds_total
model_dds <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                      waist_cm + school_bi + dds_total + (1 | house_id), stove_use_data)
#summary(model_dds)
tidy_model_dds <- tidy(model_dds, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "dds_total")

##### CPP and stove_use_3 - full model with all potential confounders
model_full <- lmer(pulse_pressure_central ~ stove_use_3 + ns(date_sphygmo, df=6) + age_baseline +
                       waist_cm + school_bi + dds_total + phys_act +
                       ses_materials + beds_new + 
                       (1 | house_id), stove_use_data)
#summary(model_full)
tidy_model_full <- tidy(model_full, conf.int = TRUE) %>% 
   filter(grepl('stove_use_3', term)) %>% 
    mutate(model = "full")



##### CPP and stove_use_days_stack

model_stove_use_days <- lmer(pulse_pressure_central ~ stove_use_days_stack + 
                        ns(date_sphygmo, df=6) + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_stove_use_days)
tidy_model_stove_use_days <- tidy(model_stove_use_days, conf.int = TRUE) %>% 
    filter(grepl('stove_use', term)) %>% 
    mutate(model = "stove use days") 


##### CPP and stove_use_hours

model_stove_use_hours <- lmer(pulse_pressure_central ~ stove_use_hours + 
                        ns(date_sphygmo, df=6) + age_baseline +
                        waist_cm + school_bi + (1 | house_id), stove_use_data)
#summary(model_stove_use_hours)
tidy_model_stove_use_hours <- tidy(model_stove_use_hours, conf.int = TRUE) %>% 
    filter(grepl('stove_use', term)) %>% 
    mutate(model = "stove use hours") 

cpp_results <- rbind(tidy_model_stove_use_3,
                     tidy_model_no_bp_meds,
                     tidy_model_6phases,
                     tidy_model_phase,
                     tidy_model_season,
                     tidy_model_spline12,
                     tidy_model_bmi,
                     tidy_model_whr,
                     tidy_model_beds,
                     tidy_model_ses,
                     tidy_model_pa,
                     tidy_model_dds,
                     tidy_model_full,
                     tidy_model_reduced,
                     tidy_model_stove_use_days,
                     tidy_model_stove_use_hours)
#kable(cpp_results)
```


