---
title: "R00 Clean Final PM Database"
author: "Ethan Walker"
date: "April 2, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
```

```{r, message=FALSE}
# Load data
r00_area_pm <- read_xlsx("input/r00_area_pm_database.xlsx")
r00_personal_pm <- read_xlsx("input/r00_personal_pm_database.xlsx")
```

##### Clean personal and area databases #####
```{r}
r00_area_pm_clean <- r00_area_pm %>% 
  rename_all(tolower) %>% 
  rename(filter_id_area = filter_id) %>% 
  separate(phase, c("p", "phase"), sep = "P") %>% 
  select(-p, -study_arm)

r00_personal_pm_clean <- r00_personal_pm %>% 
  rename_all(tolower) %>% 
  rename(filter_id_personal = filter_id, 
         cartridge_personal = cartridge, 
         cyclone_personal = cyclone) %>% 
  separate(phase, c("p", "phase"), sep = "P") %>% 
  select(-p, -study_arm)
```

# Combine personal and area databases
```{r}
r00_pm_joined <- r00_personal_pm_clean %>% 
  full_join(r00_area_pm_clean, by = c("house_id", "phase")) %>% 
  # Remove datapoint with high time-weighted average PM
  ## 10,712 ug/m3, area filter S488, phase 3
  mutate(a_twa = if_else(a_twa > 10000, 99999, a_twa)) %>% 
  replace_with_na(replace = list(a_twa = 99999))
```

# Save dataset
##### Combine with full dataset in "r00_initial_data_cleaning.rmd"
```{r}
write_rds(r00_pm_joined, "output/r00_pm_final.rds")
write_csv(r00_pm_joined, "output/r00_pm_final.csv", na = " ")
```
