---
title: "R00 Confounders Analysis"
author: "Ethan Walker"
date: "13 March 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 6)
```


```{r, message=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(pbkrtest)
library(emmeans)
library(broom)
library(purrr)
library(car)
library(forcats)
library(readxl)
library(naniar)
library(splines)
library(lubridate)
library(knitr)
library(influence.ME)
library(boxcoxmix)
jvPalette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
```

---

```{r}
#load full dataset
r00_model_data_outliers_removed <- read_rds("output/r00_model_data_outliers_removed.RDS")

# r00_full_long <- read_rds("output/r00_full_repeated_by_phase.rds")
```

```{r}
# Databases for Phases 1 and 2
r00_model_data_p1 <- r00_model_data_outliers_removed %>% 
  filter(phase == 1) %>% 
  #split age at 40; >=40 = 1, <40 = 0
  mutate(age_cat_40 = if_else(age_baseline >= 40, 1, 0)) %>% 
  #split bmi at 26; >=26 = 1, <26 = 0
  mutate(bmi_cat_26 = if_else(bmi >= 26, 1, 0)) %>% 
  #split ses assets at 2; >2 = 1, <=2 = 0
  mutate(ses_cat_2 = if_else(ses_materials > 2, 1, 0)) %>% 
  mutate(whr_cat = if_else(whr_cat == "obese", 1, 0)) %>% 
  mutate(bpp_cat = if_else(beds_new >=0.5, 1, 0)) %>% 
  mutate(dds_cat = if_else(dds_total >=6, 1, 0)) %>% 
  mutate(phys_act_cat = if_else(phys_act >=300, 1, 0)) %>% 
  mutate(salt_cat = if_else(salt >=8, 1, 0)) %>% 
  mutate(sugar_cat = if_else(sugar >=4, 1, 0)) %>% 
  mutate(manteca_cat = if_else(manteca >=7, 1, 0))

r00_model_data_p2 <- r00_model_data_outliers_removed %>% 
  filter(phase == 2) %>% 
  #split age at 40; >=40 = 1, <40 = 0
  mutate(age_cat_40 = if_else(age_baseline >= 40, 1, 0)) %>% 
  #split bmi at 26; >=26 = 1, <26 = 0
  mutate(bmi_cat_26 = if_else(bmi >= 26, 1, 0)) %>% 
  #split ses assets at 2; >2 = 1, <=2 = 0
  mutate(ses_cat_2 = if_else(ses_materials > 2, 1, 0)) %>% 
  mutate(whr_cat = if_else(whr_cat == "obese", 1, 0)) %>% 
  mutate(bpp_cat = if_else(beds_new >=0.5, 1, 0)) %>% 
  mutate(dds_cat = if_else(dds_total >=6, 1, 0)) %>% 
  mutate(phys_act_cat = if_else(phys_act >=300, 1, 0)) %>% 
  mutate(salt_cat = if_else(salt >=8, 1, 0)) %>% 
  mutate(sugar_cat = if_else(sugar >=4, 1, 0)) %>% 
  mutate(manteca_cat = if_else(manteca >=7, 1, 0))
```

# Simple linear models between potential confounders and AIx
## Running models for Phases 1 and 2, separately
```{r}
#Age - numeric
aix_age_p1 <- lm(aug_index ~ as.numeric(age_baseline), data = r00_model_data_p1)
tidy(aix_age_p1)
aix_age_p2 <- lm(aug_index ~ as.numeric(age_baseline), data = r00_model_data_p2)
tidy(aix_age_p2)

#Age - categorical
aix_age_cat_p1 <- lm(aug_index ~ as.factor(age_cat_40), data = r00_model_data_p1)
tidy(aix_age_cat_p1)
aix_age_cat_p2 <- lm(aug_index ~ as.factor(age_cat_40), data = r00_model_data_p2)
tidy(aix_age_cat_p2)

#Cook Years - categorical
aix_cook_years_p1 <- lm(aug_index ~ as.numeric(cook_years), data = r00_model_data_p1)
tidy(aix_cook_years_p1)
aix_cook_years_p2 <- lm(aug_index ~ as.numeric(cook_years), data = r00_model_data_p2)
tidy(aix_cook_years_p2)


#BMI - numeric
aix_bmi_p1 <- lm(aug_index ~ as.numeric(bmi), data = r00_model_data_p1)
tidy(aix_bmi_p1)
aix_bmi_p2 <- lm(aug_index ~ as.numeric(bmi), data = r00_model_data_p2)
tidy(aix_bmi_p2)

#BMI - categorical
aix_bmi_cat_p1 <- lm(aug_index ~ as.factor(bmi_cat_26), data = r00_model_data_p1)
tidy(aix_bmi_cat_p1)
aix_bmi_cat_p2 <- lm(aug_index ~ as.factor(bmi_cat_26), data = r00_model_data_p2)
tidy(aix_bmi_cat_p2)


#WHR - numeric
aix_whr_p1 <- lm(aug_index ~ as.numeric(whr), data = r00_model_data_p1)
tidy(aix_whr_p1)
aix_whr_p2 <- lm(aug_index ~ as.numeric(whr), data = r00_model_data_p2)
tidy(aix_whr_p2)

#WHR - categorical
aix_whr_cat_p1 <- lm(aug_index ~ as.factor(whr_cat), data = r00_model_data_p1)
tidy(aix_whr_cat_p1)
aix_whr_cat_p2 <- lm(aug_index ~ as.factor(whr_cat), data = r00_model_data_p2)
tidy(aix_whr_cat_p2)


#BPP - numeric
aix_bed_p1 <- lm(aug_index ~ as.numeric(beds_new), data = r00_model_data_p1)
tidy(aix_bed_p1)
aix_bed_p2 <- lm(aug_index ~ as.numeric(beds_new), data = r00_model_data_p2)
tidy(aix_bed_p2)

#BPP - categorical
aix_bed_cat_p1 <- lm(aug_index ~ as.factor(bpp_cat), data = r00_model_data_p1)
tidy(aix_bed_cat_p1)
aix_bed_cat_p2 <- lm(aug_index ~ as.factor(bpp_cat), data = r00_model_data_p2)
tidy(aix_bed_cat_p2)


#SES Materials - numeric
aix_ses_p1 <- lm(aug_index ~ as.numeric(ses_materials), data = r00_model_data_p1)
tidy(aix_ses_p1)
aix_ses_p2 <- lm(aug_index ~ as.numeric(ses_materials), data = r00_model_data_p2)
tidy(aix_ses_p2)

#SES Materials - categorical
aix_ses_cat_p1 <- lm(aug_index ~ as.factor(ses_cat_2), data = r00_model_data_p1)
tidy(aix_ses_cat_p1)
aix_ses_cat_p2 <- lm(aug_index ~ as.factor(ses_cat_2), data = r00_model_data_p2)
tidy(aix_ses_cat_p2)


#School years - numeric
aix_school_p1 <- lm(aug_index ~ as.numeric(school_self), data = r00_model_data_p1)
tidy(aix_school_p1)
aix_school_p2 <- lm(aug_index ~ as.numeric(school_self), data = r00_model_data_p2)
tidy(aix_school_p2)

#School - categorical
# 1 >= 6 years
aix_school_bi_p1 <- lm(aug_index ~ as.factor(school_bi), data = r00_model_data_p1)
tidy(aix_school_bi_p1)
aix_school_bi_p2 <- lm(aug_index ~ as.factor(school_bi), data = r00_model_data_p2)
tidy(aix_school_bi_p2)


#DDS - numeric
aix_dds_p1 <- lm(aug_index ~ as.numeric(dds_total), data = r00_model_data_p1)
tidy(aix_dds_p1)
aix_dds_p2 <- lm(aug_index ~ as.numeric(dds_total), data = r00_model_data_p2)
tidy(aix_dds_p2)

#DDS - categorical
aix_dds_cat_p1 <- lm(aug_index ~ as.factor(dds_cat), data = r00_model_data_p1)
tidy(aix_dds_cat_p1)
aix_dds_cat_p2 <- lm(aug_index ~ as.factor(dds_cat), data = r00_model_data_p2)
tidy(aix_dds_cat_p2)


#Phys Act - numeric
aix_phys_act_p1 <- lm(aug_index ~ as.numeric(phys_act), data = r00_model_data_p1)
tidy(aix_phys_act_p1)
aix_phys_act_p2 <- lm(aug_index ~ as.numeric(phys_act), data = r00_model_data_p2)
tidy(aix_phys_act_p2)

#Phys Act - categorical
aix_phys_act_cat_p1 <- lm(aug_index ~ as.factor(phys_act_cat), data = r00_model_data_p1)
tidy(aix_phys_act_cat_p1)
aix_phys_act_cat_p2 <- lm(aug_index ~ as.factor(phys_act_cat), data = r00_model_data_p2)
tidy(aix_phys_act_cat_p2)

#Salt - numeric
aix_salt_p1 <- lm(aug_index ~ as.numeric(salt), data = r00_model_data_p1)
tidy(aix_salt_p1)
aix_salt_p2 <- lm(aug_index ~ as.numeric(salt), data = r00_model_data_p2)
tidy(aix_salt_p2)

#Salt - categorical
aix_salt_cat_p1 <- lm(aug_index ~ as.factor(salt_cat), data = r00_model_data_p1)
tidy(aix_salt_cat_p1)
aix_salt_cat_p2 <- lm(aug_index ~ as.factor(salt_cat), data = r00_model_data_p2)
tidy(aix_salt_cat_p2)

#Sugar - numeric
aix_sugar_p1 <- lm(aug_index ~ as.numeric(sugar), data = r00_model_data_p1)
tidy(aix_sugar_p1)
aix_sugar_p2 <- lm(aug_index ~ as.numeric(sugar), data = r00_model_data_p2)
tidy(aix_sugar_p2)

#Sugar - categorical
aix_sugar_cat_p1 <- lm(aug_index ~ as.factor(sugar_cat), data = r00_model_data_p1)
tidy(aix_sugar_cat_p1)
aix_sugar_cat_p2 <- lm(aug_index ~ as.factor(sugar_cat), data = r00_model_data_p2)
tidy(aix_sugar_cat_p2)

#Manteca - numeric
aix_manteca_p1 <- lm(aug_index ~ as.numeric(manteca), data = r00_model_data_p1)
tidy(aix_manteca_p1)
aix_manteca_p2 <- lm(aug_index ~ as.numeric(manteca), data = r00_model_data_p2)
tidy(aix_manteca_p2)

#Manteca - categorical
aix_manteca_cat_p1 <- lm(aug_index ~ as.factor(manteca_cat), data = r00_model_data_p1)
tidy(aix_manteca_cat_p1)
aix_manteca_cat_p2 <- lm(aug_index ~ as.factor(manteca_cat), data = r00_model_data_p2)
tidy(aix_manteca_cat_p2)

#Kitchen temp - numeric
aix_kitchen_temp_p1 <- lm(aug_index ~ as.numeric(mean_temp), data = r00_model_data_p1)
tidy(aix_kitchen_temp_p1)
aix_kitchen_temp_p2 <- lm(aug_index ~ as.numeric(mean_temp), data = r00_model_data_p2)
tidy(aix_kitchen_temp_p2)


tidy(aix_age_p1)
tidy(aix_age_cat_p1)
tidy(aix_cook_years_p1)
tidy(aix_bmi_p1)
tidy(aix_bmi_cat_p1)
tidy(aix_whr_p1)
tidy(aix_whr_cat_p1)
tidy(aix_bed_p1)
tidy(aix_bed_cat_p1)
tidy(aix_ses_p1)
tidy(aix_ses_cat_p1)
tidy(aix_school_p1)
tidy(aix_school_bi_p1)
tidy(aix_dds_p1)
tidy(aix_dds_cat_p1)
tidy(aix_phys_act_p1)
tidy(aix_phys_act_cat_p1)
tidy(aix_salt_p1)
tidy(aix_salt_cat_p1)
tidy(aix_sugar_p1)
tidy(aix_sugar_cat_p1)
tidy(aix_manteca_p1)
tidy(aix_manteca_cat_p1)
tidy(aix_kitchen_temp_p1)
```

# Simple linear models between potential confounders and CPP
## Running models for Phases 1 and 2, separately
```{r}
#Age - numeric
cpp_age_p1 <- lm(pulse_pressure_central ~ as.numeric(age_baseline), data = r00_model_data_p1)
tidy(cpp_age_p1)
cpp_age_p2 <- lm(pulse_pressure_central ~ as.numeric(age_baseline), data = r00_model_data_p2)
tidy(cpp_age_p2)

#Age - categorical
cpp_age_cat_p1 <- lm(pulse_pressure_central ~ as.factor(age_cat_40), data = r00_model_data_p1)
tidy(cpp_age_cat_p1)
cpp_age_cat_p2 <- lm(pulse_pressure_central ~ as.factor(age_cat_40), data = r00_model_data_p2)
tidy(cpp_age_cat_p2)

#Cook Years - categorical
cpp_cook_years_p1 <- lm(pulse_pressure_central ~ as.numeric(cook_years), data = r00_model_data_p1)
tidy(cpp_cook_years_p1)
cpp_cook_years_p2 <- lm(pulse_pressure_central ~ as.numeric(cook_years), data = r00_model_data_p2)
tidy(cpp_cook_years_p2)


#BMI - numeric
cpp_bmi_p1 <- lm(pulse_pressure_central ~ as.numeric(bmi), data = r00_model_data_p1)
tidy(cpp_bmi_p1)
cpp_bmi_p2 <- lm(pulse_pressure_central ~ as.numeric(bmi), data = r00_model_data_p2)
tidy(cpp_bmi_p2)

#BMI - categorical
cpp_bmi_cat_p1 <- lm(pulse_pressure_central ~ as.factor(bmi_cat_26), data = r00_model_data_p1)
tidy(cpp_bmi_cat_p1)
cpp_bmi_cat_p2 <- lm(pulse_pressure_central ~ as.factor(bmi_cat_26), data = r00_model_data_p2)
tidy(cpp_bmi_cat_p2)


#WHR - numeric
cpp_whr_p1 <- lm(pulse_pressure_central ~ as.numeric(whr), data = r00_model_data_p1)
tidy(cpp_whr_p1)
cpp_whr_p2 <- lm(pulse_pressure_central ~ as.numeric(whr), data = r00_model_data_p2)
tidy(cpp_whr_p2)

#WHR - categorical
cpp_whr_cat_p1 <- lm(pulse_pressure_central ~ as.factor(whr_cat), data = r00_model_data_p1)
tidy(cpp_whr_cat_p1)
cpp_whr_cat_p2 <- lm(pulse_pressure_central ~ as.factor(whr_cat), data = r00_model_data_p2)
tidy(cpp_whr_cat_p2)


#BPP - numeric
cpp_bed_p1 <- lm(pulse_pressure_central ~ as.numeric(beds_new), data = r00_model_data_p1)
tidy(cpp_bed_p1)
cpp_bed_p2 <- lm(pulse_pressure_central ~ as.numeric(beds_new), data = r00_model_data_p2)
tidy(cpp_bed_p2)

#BPP - categorical
cpp_bed_cat_p1 <- lm(pulse_pressure_central ~ as.factor(bpp_cat), data = r00_model_data_p1)
tidy(cpp_bed_cat_p1)
cpp_bed_cat_p2 <- lm(pulse_pressure_central ~ as.factor(bpp_cat), data = r00_model_data_p2)
tidy(cpp_bed_cat_p2)


#SES Materials - numeric
cpp_ses_p1 <- lm(pulse_pressure_central ~ as.numeric(ses_materials), data = r00_model_data_p1)
tidy(cpp_ses_p1)
cpp_ses_p2 <- lm(pulse_pressure_central ~ as.numeric(ses_materials), data = r00_model_data_p2)
tidy(cpp_ses_p2)

#SES Materials - categorical
cpp_ses_cat_p1 <- lm(pulse_pressure_central ~ as.factor(ses_cat_2), data = r00_model_data_p1)
tidy(cpp_ses_cat_p1)
cpp_ses_cat_p2 <- lm(pulse_pressure_central ~ as.factor(ses_cat_2), data = r00_model_data_p2)
tidy(cpp_ses_cat_p2)


#School years - numeric
cpp_school_p1 <- lm(pulse_pressure_central ~ as.numeric(school_self), data = r00_model_data_p1)
tidy(cpp_school_p1)
cpp_school_p2 <- lm(pulse_pressure_central ~ as.numeric(school_self), data = r00_model_data_p2)
tidy(cpp_school_p2)

#School - categorical
# 1 >= 6 years
cpp_school_bi_p1 <- lm(pulse_pressure_central ~ as.factor(school_bi), data = r00_model_data_p1)
tidy(cpp_school_bi_p1)
cpp_school_bi_p2 <- lm(pulse_pressure_central ~ as.factor(school_bi), data = r00_model_data_p2)
tidy(cpp_school_bi_p2)


#DDS - numeric
cpp_dds_p1 <- lm(pulse_pressure_central ~ as.numeric(dds_total), data = r00_model_data_p1)
tidy(cpp_dds_p1)
cpp_dds_p2 <- lm(pulse_pressure_central ~ as.numeric(dds_total), data = r00_model_data_p2)
tidy(cpp_dds_p2)

#DDS - categorical
cpp_dds_cat_p1 <- lm(pulse_pressure_central ~ as.factor(dds_cat), data = r00_model_data_p1)
tidy(cpp_dds_cat_p1)
cpp_dds_cat_p2 <- lm(pulse_pressure_central ~ as.factor(dds_cat), data = r00_model_data_p2)
tidy(cpp_dds_cat_p2)


#Phys Act - numeric
cpp_phys_act_p1 <- lm(pulse_pressure_central ~ as.numeric(phys_act), data = r00_model_data_p1)
tidy(cpp_phys_act_p1)
cpp_phys_act_p2 <- lm(pulse_pressure_central ~ as.numeric(phys_act), data = r00_model_data_p2)
tidy(cpp_phys_act_p2)

#Phys Act - categorical
cpp_phys_act_cat_p1 <- lm(pulse_pressure_central ~ as.factor(phys_act_cat), data = r00_model_data_p1)
tidy(cpp_phys_act_cat_p1)
cpp_phys_act_cat_p2 <- lm(pulse_pressure_central ~ as.factor(phys_act_cat), data = r00_model_data_p2)
tidy(cpp_phys_act_cat_p2)

#Salt - numeric
cpp_salt_p1 <- lm(pulse_pressure_central ~ as.numeric(salt), data = r00_model_data_p1)
tidy(cpp_salt_p1)
cpp_salt_p2 <- lm(pulse_pressure_central ~ as.numeric(salt), data = r00_model_data_p2)
tidy(cpp_salt_p2)

#Salt - categorical
cpp_salt_cat_p1 <- lm(pulse_pressure_central ~ as.factor(salt_cat), data = r00_model_data_p1)
tidy(cpp_salt_cat_p1)
cpp_salt_cat_p2 <- lm(pulse_pressure_central ~ as.factor(salt_cat), data = r00_model_data_p2)
tidy(cpp_salt_cat_p2)

#Sugar - numeric
cpp_sugar_p1 <- lm(pulse_pressure_central ~ as.numeric(sugar), data = r00_model_data_p1)
tidy(cpp_sugar_p1)
cpp_sugar_p2 <- lm(pulse_pressure_central ~ as.numeric(sugar), data = r00_model_data_p2)
tidy(cpp_sugar_p2)

#Sugar - categorical
cpp_sugar_cat_p1 <- lm(pulse_pressure_central ~ as.factor(sugar_cat), data = r00_model_data_p1)
tidy(cpp_sugar_cat_p1)
cpp_sugar_cat_p2 <- lm(pulse_pressure_central ~ as.factor(sugar_cat), data = r00_model_data_p2)
tidy(cpp_sugar_cat_p2)

#Manteca - numeric
cpp_manteca_p1 <- lm(pulse_pressure_central ~ as.numeric(manteca), data = r00_model_data_p1)
tidy(cpp_manteca_p1)
cpp_manteca_p2 <- lm(pulse_pressure_central ~ as.numeric(manteca), data = r00_model_data_p2)
tidy(cpp_manteca_p2)

#Manteca - categorical
cpp_manteca_cat_p1 <- lm(pulse_pressure_central ~ as.factor(manteca_cat), data = r00_model_data_p1)
tidy(cpp_manteca_cat_p1)
cpp_manteca_cat_p2 <- lm(pulse_pressure_central ~ as.factor(manteca_cat), data = r00_model_data_p2)
tidy(cpp_manteca_cat_p2)

#Kitchen temp - numeric
cpp_kitchen_temp_p1 <- lm(pulse_pressure_central ~ as.numeric(mean_temp), data = r00_model_data_p1)
tidy(cpp_kitchen_temp_p1)
cpp_kitchen_temp_p2 <- lm(pulse_pressure_central ~ as.numeric(mean_temp), data = r00_model_data_p2)
tidy(cpp_kitchen_temp_p2)



tidy(cpp_age_p1)
tidy(cpp_age_cat_p1)
tidy(cpp_cook_years_p1)
tidy(cpp_bmi_p1)
tidy(cpp_bmi_cat_p1)
tidy(cpp_whr_p1)
tidy(cpp_whr_cat_p1)
tidy(cpp_bed_p1)
tidy(cpp_bed_cat_p1)
tidy(cpp_ses_p1)
tidy(cpp_ses_cat_p1)
tidy(cpp_school_p1)
tidy(cpp_school_bi_p1)
tidy(cpp_dds_p1)
tidy(cpp_dds_cat_p1)
tidy(cpp_phys_act_p1)
tidy(cpp_phys_act_cat_p1)
tidy(cpp_salt_p1)
tidy(cpp_salt_cat_p1)
tidy(cpp_sugar_p1)
tidy(cpp_sugar_cat_p1)
tidy(cpp_manteca_p1)
tidy(cpp_manteca_cat_p1)
tidy(cpp_kitchen_temp_p1)
```

