---
title: "BC Cleaning"
author: "Ethan Walker"
date: "November 8, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(readxl)
```

#Read in BC files
```{r, message=FALSE}
r00_phase1_bc <- read_xlsx("input/r00_phase1_bc.xlsx", 
                           col_types = c("text", "date", "text", "guess", "numeric",
                                         "numeric", "numeric", "numeric", "numeric",
                                         "numeric", "text"))
r00_phase2_bc_post <- read_csv("input/r00_phase2_bc_post.csv")
r00_phase2_bc_pre <- read_csv("input/r00_phase2_bc_pre.csv")
r00_phase3_bc_post <- read_csv("input/r00_phase3_bc_post.csv")
r00_phase3_bc_pre <- read_csv("input/r00_phase3_bc_pre.csv")
r00_phase4_bc_post <- read_csv("input/r00_phase4_bc_post.csv")
r00_phase4_bc_pre <- read_csv("input/r00_phase4_bc_pre.csv")
r00_phase5_bc_post <- read_csv("input/r00_phase5_bc_post.csv")
r00_phase5_bc_pre <- read_csv("input/r00_phase5_bc_pre.csv")
r00_phase6_bc_post <- read_csv("input/r00_phase6_bc_post.csv")
r00_phase6_bc_pre <- read_csv("input/r00_phase6_bc_pre.csv")

r00_phase1_field_data <- read_xlsx("input/r00_phase1_field_data.xlsx")
r00_phase4_field_data <- read_csv("input/r00_phase4_field_data.csv")
r00_phase5_field_data <- read_csv("input/r00_phase5_field_data.csv")

r00_phase1_bc <- read_csv("input/r00_phase1_bc.csv")
r00_phase4_bc <- read_csv("input/r00_phase4_bc.csv")
r00_phase5_bc <- read_csv("input/r00_phase5_bc.csv")
```

#Join BC files
```{r}
r00_phase2_bc <- full_join(r00_phase2_bc_pre, r00_phase2_bc_post, by = "filter_id")
# should the blank filters with ID beginning "L" actually begin "BL"?

r00_phase3_bc <- full_join(r00_phase3_bc_pre, r00_phase3_bc_post, by = "filter_id")

r00_phase4_bc <- full_join(r00_phase4_bc_pre, r00_phase4_bc_post, by = "filter_id")

r00_phase5_bc <- full_join(r00_phase5_bc_pre, r00_phase5_bc_post, by = "filter_id")

r00_phase6_bc <- full_join(r00_phase6_bc_pre, r00_phase6_bc_post, by = "filter_id")
```

#Join BC sootscan data with field data
```{r}
r00_phase1_bc_full <- full_join(r00_phase1_bc, r00_phase1_field_data, by = "filter_id")
r00_phase4_bc_full <- full_join(r00_phase4_bc, r00_phase4_field_data, by = "filter_id")
r00_phase5_bc_full <- full_join(r00_phase5_bc, r00_phase5_field_data, by = "filter_id")
```


#save data
```{r}
# Joined BC pre/post data
write_csv(r00_phase1_bc_post, "output/r00_phase1_bc.csv", na = " ") #we didn't pre-scan for phase 1
write_csv(r00_phase2_bc, "output/r00_phase2_bc.csv", na = " ")
write_csv(r00_phase3_bc, "output/r00_phase3_bc.csv", na = " ")
write_csv(r00_phase4_bc, "output/r00_phase4_bc.csv", na = " ")
write_csv(r00_phase5_bc, "output/r00_phase5_bc.csv", na = " ")
write_csv(r00_phase6_bc, "output/r00_phase6_bc.csv", na = " ")

# Joined BC with field data
write_csv(r00_phase1_bc_full, "output/r00_phase1_bc_full.csv", na = " ") #we didn't pre-scan for phase 1
write_csv(r00_phase2_bc_full, "output/r00_phase2_bc_full.csv", na = " ")
write_csv(r00_phase3_bc_full, "output/r00_phase3_bc_full.csv", na = " ")
write_csv(r00_phase4_bc_full, "output/r00_phase4_bc_full.csv", na = " ")
write_csv(r00_phase5_bc_full, "output/r00_phase5_bc_full.csv", na = " ")
write_csv(r00_phase6_bc_full, "output/r00_phase6_bc_full.csv", na = " ")
```

