---
title: "Sphygmocor Summary Stats"
author: "Ethan Walker"
date: "January 2nd, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r, message=FALSE}
library(tidyverse)
library(magrittr)
library(gridExtra)
library(lubridate)
library(haven)
library(knitr)
```

---

```{r}
#load full dataset
r00_full_joined_sphygmocor <- read_rds("output/r00_full_joined_sphygmocor.RDS")
```

## Variables grouped by study arm
```{r}
summary_hr <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "hr", mean = mean(hr), 
            sd = sd(hr), median = median(hr),
            max = max(hr), min = min(hr))

summary_sys_bp_periph <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "sys bp periph", mean = mean(sys_bp_periph), 
            sd = sd(sys_bp_periph), median = median(sys_bp_periph),
            max = max(sys_bp_periph), min = min(sys_bp_periph))

summary_dia_bp_periph <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "dia bp periph", mean = mean(dia_bp_periph), 
            sd = sd(dia_bp_periph), median = median(dia_bp_periph),
            max = max(dia_bp_periph), min = min(dia_bp_periph))

summary_map_periph <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "map periph", mean = mean(map_periph), 
            sd = sd(map_periph), median = median(map_periph),
            max = max(map_periph), min = min(map_periph))

summary_sys_bp_central <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "sys bp central", mean = mean(sys_bp_central), 
            sd = sd(sys_bp_central), median = median(sys_bp_central),
            max = max(sys_bp_central), min = min(sys_bp_central))

summary_dia_bp_central <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "dia bp central", mean = mean(dia_bp_central), 
            sd = sd(dia_bp_central), median = median(dia_bp_central),
            max = max(dia_bp_central), min = min(dia_bp_central))

summary_map_central <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "map central", mean = mean(map_central), 
            sd = sd(map_central), median = median(map_central),
            max = max(map_central), min = min(map_central))

summary_aug_pressure <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "aug pressure", mean = mean(aug_pressure), 
            sd = sd(aug_pressure), median = median(aug_pressure),
            max = max(aug_pressure), min = min(aug_pressure))

summary_aug_index <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "aug index", mean = mean(aug_index), 
            sd = sd(aug_index), median = median(aug_index),
            max = max(aug_index), min = min(aug_index))

summary_aug_index_75 <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "aug index 75", mean = mean(aug_index_75), 
            sd = sd(aug_index_75), median = median(aug_index_75),
            max = max(aug_index_75), min = min(aug_index_75))

summary_pulse_pressure_central <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "pulse pressure central", mean = mean(pulse_pressure_central), 
            sd = sd(pulse_pressure_central), median = median(pulse_pressure_central),
            max = max(pulse_pressure_central), min = min(pulse_pressure_central))

summary_pulse_pressure_periph <- r00_full_joined_sphygmocor %>% 
  select(study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(study_arm) %>% 
  summarise(variable = "pulse pressure periph", mean = mean(pulse_pressure_periph), 
            sd = sd(pulse_pressure_periph), median = median(pulse_pressure_periph),
            max = max(pulse_pressure_periph), min = min(pulse_pressure_periph))

summary <- rbind(summary_hr, summary_sys_bp_periph, summary_dia_bp_periph, 
                 summary_map_periph, summary_pulse_pressure_periph, 
                 summary_sys_bp_central, summary_dia_bp_central, 
                 summary_map_central, summary_pulse_pressure_central, 
                 summary_aug_index, summary_aug_index_75, summary_aug_pressure)
kable(summary, digits = 2)
```

## Variables grouped by phase
```{r}
summary_hr <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "hr", mean = mean(hr), 
            sd = sd(hr), median = median(hr),
            max = max(hr), min = min(hr))

summary_sys_bp_periph <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "sys bp periph", mean = mean(sys_bp_periph), 
            sd = sd(sys_bp_periph), median = median(sys_bp_periph),
            max = max(sys_bp_periph), min = min(sys_bp_periph))

summary_dia_bp_periph <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "dia bp periph", mean = mean(dia_bp_periph), 
            sd = sd(dia_bp_periph), median = median(dia_bp_periph),
            max = max(dia_bp_periph), min = min(dia_bp_periph))

summary_map_periph <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "map periph", mean = mean(map_periph), 
            sd = sd(map_periph), median = median(map_periph),
            max = max(map_periph), min = min(map_periph))

summary_sys_bp_central <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "sys bp central", mean = mean(sys_bp_central), 
            sd = sd(sys_bp_central), median = median(sys_bp_central),
            max = max(sys_bp_central), min = min(sys_bp_central))

summary_dia_bp_central <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "dia bp central", mean = mean(dia_bp_central), 
            sd = sd(dia_bp_central), median = median(dia_bp_central),
            max = max(dia_bp_central), min = min(dia_bp_central))

summary_map_central <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "map central", mean = mean(map_central), 
            sd = sd(map_central), median = median(map_central),
            max = max(map_central), min = min(map_central))

summary_aug_pressure <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "aug pressure", mean = mean(aug_pressure), 
            sd = sd(aug_pressure), median = median(aug_pressure),
            max = max(aug_pressure), min = min(aug_pressure))

summary_aug_index <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "aug index", mean = mean(aug_index), 
            sd = sd(aug_index), median = median(aug_index),
            max = max(aug_index), min = min(aug_index))

summary_aug_index_75 <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "aug index 75", mean = mean(aug_index_75), 
            sd = sd(aug_index_75), median = median(aug_index_75),
            max = max(aug_index_75), min = min(aug_index_75))

summary_pulse_pressure_central <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "pulse pressure central", mean = mean(pulse_pressure_central), 
            sd = sd(pulse_pressure_central), median = median(pulse_pressure_central),
            max = max(pulse_pressure_central), min = min(pulse_pressure_central))

summary_pulse_pressure_periph <- r00_full_joined_sphygmocor %>% 
  select(phase, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index) %>% 
  group_by(phase) %>% 
  summarise(variable = "pulse pressure periph", mean = mean(pulse_pressure_periph), 
            sd = sd(pulse_pressure_periph), median = median(pulse_pressure_periph),
            max = max(pulse_pressure_periph), min = min(pulse_pressure_periph))

summary <- rbind(summary_hr, summary_sys_bp_periph, summary_dia_bp_periph, 
                 summary_map_periph, summary_pulse_pressure_periph, 
                 summary_sys_bp_central, summary_dia_bp_central, 
                 summary_map_central, summary_pulse_pressure_central, 
                 summary_aug_index, summary_aug_index_75, summary_aug_pressure)
kable(summary, digits = 2)
```

## Correlation Matrix
```{r}
summary_correlation <- r00_full_joined_sphygmocor %>% 
  select(aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>% 
  na.exclude(aug_index)
cor(summary_correlation)
```

## Boxplots by phase
#### Means marked and labeled in red  
```{r, fig.width=10}
# summary to include in plots below (geom_text)
sphygmocor_means <- r00_full_joined_sphygmocor %>% 
  select(phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  group_by(phase, study_arm) %>% 
  summarise(mean(aug_index), sd(aug_index), 
            mean(aug_index_75), sd(aug_index_75),
            mean(hr), sd(hr), 
            mean(pulse_pressure_central), sd(pulse_pressure_central), 
            mean(pulse_pressure_periph), sd(pulse_pressure_periph), 
            mean(sys_bp_central), sd(sys_bp_central), 
            mean(dia_bp_central), sd(dia_bp_central),
            mean(sys_bp_periph), sd(sys_bp_periph), 
            mean(dia_bp_periph), sd(dia_bp_periph)) %>% 
  arrange(study_arm)
#sphygmocor_means

## AIx
# boxplots by phase, faceted by study arm
# means plotted in red
sphygmocor_boxplot <- r00_full_joined_sphygmocor %>% 
  select(phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot(aes(phase, aug_index)) +
  geom_boxplot(aes(phase, aug_index)) +
  facet_wrap(~study_arm) +
  geom_text(data = sphygmocor_means, aes(phase, `mean(aug_index)`, 
                                    label = round(`mean(aug_index)`, digits = 2)), 
            size = 4, vjust = -1.5, color = "red") +
  geom_point(data = sphygmocor_means, aes(phase, `mean(aug_index)`), 
            size = 2, color = "red") +
  ggtitle("AIx by Phase and Study Arm", subtitle = "means in red") +
  theme_minimal()
sphygmocor_boxplot


## HR
# boxplots by phase, faceted by study arm
# means plotted in red
sphygmocor_boxplot <- r00_full_joined_sphygmocor %>% 
  select(phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot(aes(phase, hr)) +
  geom_boxplot(aes(phase, hr)) +
  facet_wrap(~study_arm) +
  geom_text(data = sphygmocor_means, aes(phase, `mean(hr)`, 
                                    label = round(`mean(hr)`, digits = 2)), 
            size = 4, vjust = -1.5, color = "red") +
  geom_point(data = sphygmocor_means, aes(phase, `mean(hr)`), 
            size = 2, color = "red") +
  ggtitle("HR by Phase and Study Arm", subtitle = "means in red") +
  theme_minimal()
sphygmocor_boxplot


## Central Pulse Pressure
# boxplots by phase, faceted by study arm
# means plotted in red
sphygmocor_boxplot <- r00_full_joined_sphygmocor %>% 
  select(phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot(aes(phase, pulse_pressure_central)) +
  geom_boxplot(aes(phase, pulse_pressure_central)) +
  facet_wrap(~study_arm) +
  geom_text(data = sphygmocor_means, aes(phase, `mean(pulse_pressure_central)`, 
                                    label = round(`mean(pulse_pressure_central)`, digits = 2)), 
            size = 4, vjust = -1.5, color = "red") +
  geom_point(data = sphygmocor_means, aes(phase, `mean(pulse_pressure_central)`), 
            size = 2, color = "red") +
  ggtitle("Central Pulse Pressure by Phase and Study Arm", subtitle = "means in red") +
  theme_minimal()
sphygmocor_boxplot


## Central Systolic Pressure
# boxplots by phase, faceted by study arm
# means plotted in red
sphygmocor_boxplot <- r00_full_joined_sphygmocor %>% 
  select(phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot(aes(phase, sys_bp_central)) +
  geom_boxplot(aes(phase, sys_bp_central)) +
  facet_wrap(~study_arm) +
  geom_text(data = sphygmocor_means, aes(phase, `mean(sys_bp_central)`, 
                                    label = round(`mean(sys_bp_central)`, digits = 2)), 
            size = 4, vjust = -1.5, color = "red") +
  geom_point(data = sphygmocor_means, aes(phase, `mean(sys_bp_central)`), 
            size = 2, color = "red") +
  ggtitle("Central Systolic BP by Phase and Study Arm", subtitle = "means in red") +
  theme_minimal()
sphygmocor_boxplot


## Central Diastolic Pressure
# boxplots by phase, faceted by study arm
# means plotted in red
sphygmocor_boxplot <- r00_full_joined_sphygmocor %>% 
  select(phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  ggplot(aes(phase, dia_bp_central)) +
  geom_boxplot(aes(phase, dia_bp_central)) +
  facet_wrap(~study_arm) +
  geom_text(data = sphygmocor_means, aes(phase, `mean(dia_bp_central)`, 
                                    label = round(`mean(dia_bp_central)`, digits = 2)),
                                    size = 4, vjust = -1.5, color = "red") +
  geom_point(data = sphygmocor_means, aes(phase, `mean(dia_bp_central)`), 
            size = 2, color = "red") +
  ggtitle("Central Diastolic BP by Phase and Study Arm", subtitle = "means in red") +
  theme_minimal()
sphygmocor_boxplot
```

#####   Pick up here and figure out how to plot lines from phase to phase 
## Line plots
#### Outcomes plotted across phases, faceted by study arm  
```{r}
# AIx
sphygmocor_line_plots <- ggplot(r00_full_joined_sphygmocor) +
  geom_line(aes(timepoint, aug_index, color = id, group = id)) +
  facet_wrap(~treatment_recieved) +
  theme_minimal() +
  theme(legend.position = "none")
lipids_timepoint_facetstove

sphygmocor_lineplot <- r00_full_joined_sphygmocor %>% 
  select(house_id, phase, study_arm, aug_index, hr, sys_bp_periph, dia_bp_periph, map_periph,
         sys_bp_central, dia_bp_central, map_central, aug_pressure, aug_index_75,
         pulse_pressure_periph, pulse_pressure_central) %>%
  na.exclude(aug_index) %>% 
  mutate(study_arm = factor(study_arm, levels = c(1, 2), labels = c("Arm 1", "Arm 2"))) %>% 
  group_by(phase) %>% 
  ggplot() +
  geom_path(aes(phase, mean(aug_index), group = study_arm, color = study_arm)) +
  theme_minimal() +
  theme(legend.position = "right")
sphygmocor_lineplot
```
