---
title: "SUMs Data Cleaning"
author: "Ethan Walker"
date: "August 16, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
library(caTools)
```

```{r, message=FALSE}
exposure_times <- read_csv("input/honduras_r00_exposure_times.csv")

r00_full_repeated_by_phase <- read_rds("output/r00_full_repeated_by_phase.rds")
```

#Prep Exposure Times
```{r}
exposure_times_clean <- exposure_times %>% 
  unite(setup_datetime, c(setup_date, setup_time), sep = " ") %>% 
  mutate(setup_datetime = mdy_hms(setup_datetime)) %>%
  unite(takedown_datetime, c(takedown_date, takedown_time), sep = " ") %>% 
  mutate(takedown_datetime = mdy_hms(takedown_datetime)) 

#20 NA occurrences for both setup and takedown datetimes
```

#Read in SUMs files
```{r}
setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data R00/original data/Phase 1 - Aug-Dec 2015/SUMs")

phase_1_data <- do.call("rbind", sapply(list.files(pattern = ".csv$", full.names = TRUE), 
                                     read_csv, col_names = TRUE, col_types = cols(), skip = 19, simplify = FALSE)) 
phase_1_data$mycolumn <- substring(row.names(phase_1_data),1,10)

setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data R00/original data/Phase 2 - Jan-May 2016/SUMs")

phase_2_data <- do.call("rbind", sapply(list.files(pattern = ".csv$", full.names = TRUE), 
                                     read_csv, col_names = TRUE, col_types = cols(), skip = 19, simplify = FALSE)) 
phase_2_data$mycolumn <- substring(row.names(phase_2_data),1,10)

setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data R00/original data/Phase 3 - Sep-Dec 2016/SUMs")

phase_3_data <- do.call("rbind", sapply(list.files(pattern = ".csv$", full.names = TRUE), 
                                     read_csv, col_names = TRUE, col_types = cols(), skip = 19, simplify = FALSE)) 
phase_3_data$mycolumn <- substring(row.names(phase_3_data),1,10)

setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data R00/original data/Phase 4 - Feb-May 2017/SUMs")

phase_4_data <- do.call("rbind", sapply(list.files(pattern = ".csv$", full.names = TRUE), 
                                     read_csv, col_names = TRUE, col_types = cols(), skip = 19, simplify = FALSE)) 
phase_4_data$mycolumn <- substring(row.names(phase_4_data),1,10)

setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data R00/original data/Phase 5 - Aug-Dec 2017/SUMs")

phase_5_data <- do.call("rbind", sapply(list.files(pattern = ".csv$", full.names = TRUE), 
                                     read_csv, col_names = TRUE, col_types = cols(), skip = 19, simplify = FALSE)) 
phase_5_data$mycolumn <- substring(row.names(phase_5_data),1,10)

setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data R00/original data/Phase 6 - Feb-May 2018/SUMs")

phase_6_data <- do.call("rbind", sapply(list.files(pattern = ".csv$", full.names = TRUE), 
                                     read_csv, col_names = TRUE, col_types = cols(), skip = 19, simplify = FALSE)) 
phase_6_data$mycolumn <- substring(row.names(phase_6_data),1,10)
```

#Clean SUMs files
```{r}
rownames(phase_1_data) <- c()
phase_1_data_clean <- phase_1_data %>% 
  separate(mycolumn, c("trash", "house_id"), sep = "./") %>% 
  separate(house_id, c("house_id", "prim_or_sec"), sep = "_") %>% 
  rename(datetime = `Date/Time`, temp = Value) %>% 
  select(-Unit, - trash) %>% 
  mutate(exposure_datetime = mdy_hms(datetime)) 

rownames(phase_2_data) <- c()
phase_2_data_clean <- phase_2_data %>% 
  separate(mycolumn, c("trash", "house_id"), sep = "./") %>% 
  separate(house_id, c("house_id", "prim_or_sec"), sep = "_") %>% 
  rename(datetime = `Date/Time`, temp = Value) %>% 
  select(-Unit, - trash) %>% 
  mutate(exposure_datetime = mdy_hms(datetime)) 

rownames(phase_3_data) <- c()
phase_3_data_clean <- phase_3_data %>% 
  separate(mycolumn, c("trash", "house_id"), sep = "./") %>% 
  separate(house_id, c("house_id", "prim_or_sec"), sep = "_") %>% 
  rename(datetime = `Date/Time`, temp = Value) %>% 
  select(-Unit, - trash) %>% 
  mutate(exposure_datetime = mdy_hms(datetime)) 

rownames(phase_4_data) <- c()
phase_4_data_clean <- phase_4_data %>% 
  separate(mycolumn, c("trash", "house_id"), sep = "./") %>% 
  separate(house_id, c("house_id", "prim_or_sec"), sep = "_") %>% 
  rename(datetime = `Date/Time`, temp = Value) %>% 
  select(-Unit, - trash) %>% 
  mutate(exposure_datetime = mdy_hms(datetime)) 

rownames(phase_5_data) <- c()
phase_5_data_clean <- phase_5_data %>% 
  separate(mycolumn, c("trash", "house_id"), sep = "./") %>% 
  separate(house_id, c("house_id", "prim_or_sec"), sep = "_") %>% 
  rename(datetime = `Date/Time`, temp = Value) %>% 
  select(-Unit, - trash) %>% 
  mutate(exposure_datetime = mdy_hms(datetime)) 

rownames(phase_6_data) <- c()
phase_6_data_clean <- phase_6_data %>% 
  separate(mycolumn, c("trash", "house_id"), sep = "./") %>% 
  separate(house_id, c("house_id", "prim_or_sec"), sep = "_") %>% 
  rename(datetime = `Date/Time`, temp = Value) %>% 
  select(-Unit, - trash) %>% 
  mutate(exposure_datetime = mdy_hms(datetime)) 
```

#Select for specified exposure times and add vars for specific temp thresholds
```{r}
phase_1_data_full <- exposure_times_clean %>% 
  full_join(phase_1_data_clean, by = c("house_id")) %>% 
  group_by(house_id) %>% 
  mutate(logic_datetime = if_else((exposure_datetime > setup_datetime) & 
                              (exposure_datetime < takedown_datetime), 
                              "keep", "trash")) %>% 
  filter(logic_datetime == "keep") %>% 
  select(-datetime) %>% 
  mutate(temp_35 = if_else(temp >= 35, TRUE, FALSE)) %>% 
  mutate(temp_38 = if_else(temp >= 38, TRUE, FALSE)) %>% 
  mutate(temp_40 = if_else(temp >= 40, TRUE, FALSE)) %>% 
  mutate(temp_45 = if_else(temp >= 45, TRUE, FALSE)) %>% 
  mutate(temp_50 = if_else(temp >= 50, TRUE, FALSE))

phase_2_data_full <- exposure_times_clean %>% 
  full_join(phase_2_data_clean, by = c("house_id")) %>% 
  group_by(house_id) %>% 
  mutate(logic_datetime = if_else((exposure_datetime > setup_datetime) & 
                              (exposure_datetime < takedown_datetime), 
                              "keep", "trash")) %>% 
  filter(logic_datetime == "keep") %>% 
  select(-datetime) %>% 
  mutate(temp_35 = if_else(temp >= 35, TRUE, FALSE)) %>% 
  mutate(temp_38 = if_else(temp >= 38, TRUE, FALSE)) %>% 
  mutate(temp_40 = if_else(temp >= 40, TRUE, FALSE)) %>% 
  mutate(temp_45 = if_else(temp >= 45, TRUE, FALSE)) %>% 
  mutate(temp_50 = if_else(temp >= 50, TRUE, FALSE))

phase_3_data_full <- exposure_times_clean %>% 
  full_join(phase_3_data_clean, by = c("house_id")) %>% 
  group_by(house_id) %>% 
  mutate(logic_datetime = if_else((exposure_datetime > setup_datetime) & 
                              (exposure_datetime < takedown_datetime), 
                              "keep", "trash")) %>% 
  filter(logic_datetime == "keep") %>% 
  select(-datetime) %>% 
  mutate(temp_35 = if_else(temp >= 35, TRUE, FALSE)) %>% 
  mutate(temp_38 = if_else(temp >= 38, TRUE, FALSE)) %>% 
  mutate(temp_40 = if_else(temp >= 40, TRUE, FALSE)) %>% 
  mutate(temp_45 = if_else(temp >= 45, TRUE, FALSE)) %>% 
  mutate(temp_50 = if_else(temp >= 50, TRUE, FALSE))

phase_4_data_full <- exposure_times_clean %>% 
  full_join(phase_4_data_clean, by = c("house_id")) %>% 
  group_by(house_id) %>% 
  mutate(logic_datetime = if_else((exposure_datetime > setup_datetime) & 
                              (exposure_datetime < takedown_datetime), 
                              "keep", "trash")) %>% 
  filter(logic_datetime == "keep") %>% 
  select(-datetime) %>% 
  mutate(temp_35 = if_else(temp >= 35, TRUE, FALSE)) %>% 
  mutate(temp_38 = if_else(temp >= 38, TRUE, FALSE)) %>% 
  mutate(temp_40 = if_else(temp >= 40, TRUE, FALSE)) %>% 
  mutate(temp_45 = if_else(temp >= 45, TRUE, FALSE)) %>% 
  mutate(temp_50 = if_else(temp >= 50, TRUE, FALSE))

phase_5_data_full <- exposure_times_clean %>% 
  full_join(phase_5_data_clean, by = c("house_id")) %>% 
  group_by(house_id) %>% 
  mutate(logic_datetime = if_else((exposure_datetime > setup_datetime) & 
                              (exposure_datetime < takedown_datetime), 
                              "keep", "trash")) %>% 
  filter(logic_datetime == "keep") %>% 
  select(-datetime) %>% 
  mutate(temp_35 = if_else(temp >= 35, TRUE, FALSE)) %>% 
  mutate(temp_38 = if_else(temp >= 38, TRUE, FALSE)) %>% 
  mutate(temp_40 = if_else(temp >= 40, TRUE, FALSE)) %>% 
  mutate(temp_45 = if_else(temp >= 45, TRUE, FALSE)) %>% 
  mutate(temp_50 = if_else(temp >= 50, TRUE, FALSE))

phase_6_data_full <- exposure_times_clean %>% 
  full_join(phase_6_data_clean, by = c("house_id")) %>% 
  group_by(house_id) %>% 
  mutate(logic_datetime = if_else((exposure_datetime > setup_datetime) & 
                              (exposure_datetime < takedown_datetime), 
                              "keep", "trash")) %>% 
  filter(logic_datetime == "keep") %>% 
  select(-datetime) %>% 
  mutate(temp_35 = if_else(temp >= 35, TRUE, FALSE)) %>% 
  mutate(temp_38 = if_else(temp >= 38, TRUE, FALSE)) %>% 
  mutate(temp_40 = if_else(temp >= 40, TRUE, FALSE)) %>% 
  mutate(temp_45 = if_else(temp >= 45, TRUE, FALSE)) %>% 
  mutate(temp_50 = if_else(temp >= 50, TRUE, FALSE))
```

#Save data
```{r}
write_rds(phase_1_data_full, "output/r00_phase_1_sums_data.rds")
write_csv(phase_1_data_full, "output/r00_phase_1_sums_data.csv")

write_rds(phase_2_data_full, "output/r00_phase_2_sums_data.rds")
write_csv(phase_2_data_full, "output/r00_phase_2_sums_data.csv")

write_rds(phase_3_data_full, "output/r00_phase_3_sums_data.rds")
write_csv(phase_3_data_full, "output/r00_phase_3_sums_data.csv")

write_rds(phase_4_data_full, "output/r00_phase_4_sums_data.rds")
write_csv(phase_4_data_full, "output/r00_phase_4_sums_data.csv")

write_rds(phase_5_data_full, "output/r00_phase_5_sums_data.rds")
write_csv(phase_5_data_full, "output/r00_phase_5_sums_data.csv")

write_rds(phase_6_data_full, "output/r00_phase_6_sums_data.rds")
write_csv(phase_6_data_full, "output/r00_phase_6_sums_data.csv")
```

#Analyze datasets and create final variables
```{r}
#Combine data from all phases into single dataset
sums_all_phases_full <- rbind(phase_1_data_full, phase_2_data_full, phase_3_data_full, 
                             phase_4_data_full, phase_5_data_full, phase_6_data_full)

write_rds(sums_all_phases_full, "output/r00_sums_all_phases_full.rds")
write_csv(sums_all_phases_full, "output/r00_sums_all_phases_full.csv")
```

```{r}
sums_all_phases_clean <- sums_all_phases %>% 
  #relabel temp vars: 1=true, 0=false
  mutate(temp_35 = if_else(temp_35 == TRUE, 1, 0)) %>%
  mutate(temp_38 = if_else(temp_38 == TRUE, 1, 0)) %>%
  mutate(temp_40 = if_else(temp_40 == TRUE, 1, 0)) %>%
  mutate(temp_45 = if_else(temp_45 == TRUE, 1, 0)) %>%
  mutate(temp_50 = if_else(temp_50 == TRUE, 1, 0)) %>% 
  group_by(house_id, phase, prim_or_sec) %>% 
  #create percent usage vars
  mutate(temp_35_percent = mean(temp_35)) %>% 
  mutate(temp_38_percent = mean(temp_38)) %>%
  mutate(temp_40_percent = mean(temp_40)) %>%
  mutate(temp_45_percent = mean(temp_45)) %>%
  mutate(temp_50_percent = mean(temp_50))

write_rds(sums_all_phases_clean, "output/r00_sums_all_phases_clean.rds")
write_csv(sums_all_phases_clean, "output/r00_sums_all_phases_clean.csv")

#create new var for events of temp > 38
sums_temp38_clean <- sums_all_phases_clean %>% 
  filter(prim_or_sec == "P") %>% 
  group_by(house_id, phase) %>%
  filter(temp_38 == 1) %>% 
  mutate(exposure_datetime_lead = lead(exposure_datetime)) %>% 
  mutate(time_diff = exposure_datetime_lead - exposure_datetime) %>% 
  mutate(temp_38_new_event = if_else(time_diff > 3600, 1, 0)) %>% 
  group_by(house_id, phase, temp_38_percent) %>% 
  na.omit(temp_38_new_event) %>% 
  summarise(sum(temp_38_new_event)) %>% 
  mutate(temp_38_cooking_events = `sum(temp_38_new_event)` + 1) %>% 
  select(-`sum(temp_38_new_event)`) %>% 
  ungroup() %>% 
  mutate(phase = as.character(phase)) %>% 
  rename(sums_temp38_events = temp_38_cooking_events, 
         sums_temp38_percent = temp_38_percent)

write_rds(sums_temp38_clean, "output/r00_sums_temp38_clean.rds")
write_csv(sums_temp38_clean, "output/r00_sums_temp38_clean.csv")
```

#Add to full R00 dataset
```{r}
r00_full_dataset <- r00_full_repeated_by_phase %>% 
  full_join(sums_temp38_clean, by = c("house_id", "phase"))
```

#Save final dataset
```{r}
write_rds(r00_full_dataset, "output/r00_full_repeated_by_phase.rds")
write_csv(r00_full_dataset, "output/r00_full_repeated_by_phase.csv", na = " ")
```

