---
title: "symptoms Analysis R21"
author: "Ethan Walker"
date: "14 Dec, 2018"
output: pdf_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(tidyverse)
library(emmeans)
```

```{r}
#read in dataset
setwd("T:/Rsch-Clark/Honduras Cookstove Projects/Data/Data Analysis R21/Analysis_R21_Symptoms")
honduras <- read_csv("r21final_27June2018_hr.csv")
#head(honduras)
```

#Summary PM by stove type
```{r}
summary_apm <- honduras %>% 
  select(primarystove_r21, a_pm25_r21new, p_pm25_r21new) %>% 
  mutate(apm = as.numeric(a_pm25_r21new)) %>% 
  mutate(ppm = as.numeric(p_pm25_r21new)) %>% 
  na.exclude(a_pm25_r21new) %>% 
  group_by(primarystove_r21) %>% 
  summarise(mean_apm = mean(a_pm25_r21new), n())
summary_apm

summary_ppm <- honduras %>% 
  select(primarystove_r21, a_pm25_r21new, p_pm25_r21new) %>% 
  mutate(apm = as.numeric(a_pm25_r21new)) %>% 
  mutate(ppm = as.numeric(p_pm25_r21new)) %>% 
  na.exclude(p_pm25_r21new) %>% 
  group_by(primarystove_r21) %>% 
  summarise(mean_ppm = mean(p_pm25_r21new), n())
summary_ppm
```

#Boxplots for PM
```{r}
honduras_boxplots <- honduras %>% 
  mutate(generalstove_type = factor(generalstove_type, labels = c("Justa", "Traditional"))) %>% 
  ggplot() +
  geom_boxplot(aes(x = "Personal", y = p_pm25_r21new, 
                   fill = generalstove_type), lwd = 1, fatten = 1) +
  geom_boxplot(aes(x = "Kitchen", y = a_pm25_r21new, 
                   fill = generalstove_type), lwd = 1, fatten = 1) +
  labs(aes(x="", y="")) +
  labs(aes(x = "", y = paste("PM"[2.5], " (", mu, g/m^3, ")"), fill = "Stove Type")) +
  scale_fill_manual(values = c("white", "grey")) +
  scale_y_continuous(limits = c(0, 1000)) +
  theme(axis.line.x = element_line(size = 1, colour = "black"),
        axis.line.y = element_line(size = 1, colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        text = element_text(size = 20),
        axis.text.y = element_text(size = 20, colour = "black"),
        axis.text.x = element_text(size = 20, colour = "black"),
        legend.position=c(.8,.8),
        legend.key = element_rect(fill = "white"),
        legend.text = element_text(size = 18))
honduras_boxplots 
```

#Prepping data for symptoms
```{r}
honduras_symptoms <- honduras %>% 
  select(house_id, generalstove_type, healtheyes_cooking, healthblurred_cooking,
         healthnose_cooking, healthmucous_cooking, healthcough_cooking,
         healthbreathing_cooking, healthheadache_cooking, healthchest_cooking,
         healththroat_cooking) %>% 
  gather("symptoms", "outcome", 3:11) %>% 
  mutate(symptoms = factor(symptoms, levels = c("healthheadache_cooking", "healtheyes_cooking", 
                                                "healthblurred_cooking", "healthnose_cooking", 
                                                "healthcough_cooking", "healththroat_cooking", 
                                                "healthchest_cooking", "healthbreathing_cooking", 
                                                 "healthmucous_cooking"),
                           labels = c("Headache", "Eye Irritation", "Blurred Vision",  
                                      "Nose Irritation", "Cough", "Throat Irritation", 
                                      "Chest Wheezing", "Difficulty Breathing", "Mucous Production"))) %>% 
  mutate(outcome = factor(outcome, levels = c("no", "yes"), labels = c("No", "Yes")))
  
head(honduras_symptoms)
```

#Faceted bar plots for symptoms
```{r}
honduras_barplot <- honduras_symptoms %>% 
  filter(outcome == "Yes") %>% 
  ggplot() +
  geom_bar(aes(x = "symptoms", fill = generalstove_type), position = "dodge", width = 1, color = "black", size = 1.5) +
  facet_wrap(~ symptoms) +
  labs(aes(x = "", y = "", 
           fill = "Stove Type")) +
  scale_fill_manual(values = alpha(c("skyblue", "orange"))) +
  scale_y_continuous(limits = c(0, 75)) +
  theme_few() +
  theme(axis.line.x = element_line(size = 1.5, colour = "black"),
        axis.line.y = element_line(size = 1.5, colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank())
honduras_barplot  
```

#Plots for ORs
```{r}
#Create vectors
symptoms <- c("Headache", "Nose Irritation", "Mucus Production",
              "Difficulty Breathing", "Throat Irritation", "Cough",
              "Chest Wheezing", "Blurred Vision", "Eye Irritation")
or_stove <- c(2.23, 2.29, 2.33, 1.69, 2.41, 3.12, 2.22, 3.67, 3.04)
upper_cl_stove <- c(4.39, 4.79, 6.02, 4.09, 5.25, 6.70, 5.45, 7.82, 5.99)
lower_cl_stove <- c(1.13, 1.09, 0.90, 0.70, 1.11, 1.45, 0.91, 1.72, 1.55)
or_personal_pm <- c(1.16, 1.11, 1.41, 0.81, 0.60, 0.94, 1.34, 1.19, 1.41)
upper_cl_personal_pm <- c(1.93, 1.86, 2.59, 1.57, 1.10, 1.55, 2.37, 2.01, 2.37)
lower_cl_personal_pm <- c(0.70, 0.67, 0.77, 0.42, 0.33, 0.57, 0.76, 0.70, 0.84)
or_plots <- data.frame(symptoms, or_stove, upper_cl_stove, lower_cl_stove,
                       or_personal_pm, upper_cl_personal_pm, lower_cl_personal_pm)

#Plot for Stove Type
or_plot_stoves <- ggplot() +
  geom_errorbarh(aes(x = or_stove, y = c(1:9), xmin = lower_cl_stove,
                     xmax = upper_cl_stove), size = 1) +
  geom_point(aes(x = or_stove, y = c(1:9)), size = 2, color = "black") +
  geom_vline(aes(xintercept = 1), linetype = 3, size = 1) +
  scale_x_continuous(name = "Odds Ratios with 95% Confidence Intervals",
                     breaks = c(0,1,2,3,4,5,6,7,8)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7,8,9), labels = symptoms) +
  #labs(title = "Association Between Symptoms and Stove Type") +
  labs(y = "") +
  theme(axis.line.x = element_line(size = 1, colour = "black"),
        axis.line.y = element_line(size = 1, colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_text(size = 20, colour = "black"),
        axis.text.x = element_text(size = 20, colour = "black"),
        text = element_text(size = 20))
or_plot_stoves

#Plot for Personal PM
or_plot_personal_pm <- ggplot() +
  geom_errorbarh(aes(x = or_personal_pm, y = c(1:9), xmin = lower_cl_personal_pm,
                     xmax = upper_cl_personal_pm), size = 1) +
  geom_point(aes(x = or_personal_pm, y = c(1:9)), size = 2, color = "black") +
  geom_vline(aes(xintercept = 1), linetype = 3, size = 1) +
  scale_x_continuous(name = "Odds Ratios with 95% Confidence Intervals",
                     breaks = c(0.5,1,1.5,2,2.5,3)) +
  scale_y_continuous(breaks = c(1,2,3,4,5,6,7,8,9), labels = symptoms) +
  #labs(title = "Association Between Symptoms and Personal Fine Particulate Matter Exposure") +
  labs(y = "") +
  theme(axis.line.x = element_line(size = 1, colour = "black"),
        axis.line.y = element_line(size = 1, colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        axis.text.y = element_text(size = 20, colour = "black"),
        axis.text.x = element_text(size = 20, colour = "black"),
        text = element_text(size = 20))
or_plot_personal_pm
```
